import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Clock3, Plus, Search, ShieldCheck, X, XCircle } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Approval={id:string;request_type:string;status:'pending'|'approved'|'rejected'|'cancelled';requested_by:string;authorized_by:string|null;reason:string;entity_type:string|null;entity_id:string|null;requested_value:number|string|null;decision_notes:string|null;requested_at:string;decided_at:string|null}
const labels:Record<string,string>={discount_over_limit:'Descuento superior al límite',large_purchase:'Compra grande',urgent_purchase:'Compra urgente',negative_inventory:'Inventario negativo',delivery_with_balance:'Entrega con saldo pendiente',below_margin_price:'Precio debajo del margen',other:'Otra excepción'}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})

export function ApprovalsPage({businessId,userId}:{businessId:string;userId:string}){
 const [items,setItems]=useState<Approval[]>([]),[query,setQuery]=useState(''),[modal,setModal]=useState(false),[decision,setDecision]=useState<Approval|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 async function load(){if(!supabase)return;setLoading(true);setError(null);const {data,error}=await supabase.from('approval_requests').select('id,request_type,status,requested_by,authorized_by,reason,entity_type,entity_id,requested_value,decision_notes,requested_at,decided_at').eq('business_id',businessId).order('requested_at',{ascending:false});if(error)setError(error.message);setItems((data??[]) as Approval[]);setLoading(false)}
 useEffect(()=>{void load()},[businessId])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(x=>!q||[labels[x.request_type]||x.request_type,x.reason,x.status].some(v=>v.toLowerCase().includes(q)))},[items,query])
 return <>
  <div className="page-heading page-heading--actions"><div><span className="eyebrow">Control interno</span><h1>Autorizaciones</h1><p>Excepciones que requieren revisión antes de continuar.</p></div><button className="primary-button primary-button--auto" onClick={()=>setModal(true)}><Plus size={17}/>Nueva solicitud</button></div>
  <div className="toolbar"><div className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar solicitud…"/></div><span className="toolbar__count">{visible.length} solicitudes</span></div>{error&&<div className="notice notice--error">{error}</div>}
  <div className="data-card"><div className="data-list">{loading?<div className="empty-state">Cargando…</div>:visible.length===0?<div className="empty-state"><ShieldCheck size={28}/><strong>Sin solicitudes</strong></div>:visible.map(x=><button className="data-row" key={x.id} onClick={()=>x.status==='pending'&&setDecision(x)}><div className="data-row__avatar">{x.status==='approved'?<CheckCircle2 size={18}/>:x.status==='rejected'?<XCircle size={18}/>:<Clock3 size={18}/>}</div><div className="data-row__main"><strong>{labels[x.request_type]||x.request_type}</strong><span>{x.reason}</span></div><div className="data-row__meta"><strong>{x.requested_value==null?'—':money.format(Number(x.requested_value))}</strong><span className={`badge ${x.status==='approved'?'badge--success':''}`}>{statusLabel(x.status)}</span></div></button>)}</div></div>
  {modal&&<RequestModal businessId={businessId} userId={userId} close={()=>setModal(false)} done={async()=>{setModal(false);await load()}}/>}
  {decision&&<DecisionModal request={decision} userId={userId} close={()=>setDecision(null)} done={async()=>{setDecision(null);await load()}}/>}
 </>
}
function statusLabel(s:Approval['status']){return s==='pending'?'Pendiente':s==='approved'?'Aprobada':s==='rejected'?'Rechazada':'Cancelada'}
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="form-modal form-modal--small"><div className="drawer-header"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={19}/></button></div>{children}</div></div>}
function RequestModal({businessId,userId,close,done}:{businessId:string;userId:string;close:()=>void;done:()=>void}){const [type,setType]=useState('discount_over_limit'),[reason,setReason]=useState(''),[value,setValue]=useState(''),[entityType,setEntityType]=useState(''),[entityId,setEntityId]=useState(''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('approval_requests').insert({business_id:businessId,request_type:type,requested_by:userId,reason:reason.trim(),requested_value:value===''?null:Number(value),entity_type:entityType.trim()||null,entity_id:entityId.trim()||null});if(error)setError(error.message);else done()}return <Shell title="Nueva solicitud" close={close}><form className="entity-form" onSubmit={submit}><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Motivo<textarea required rows={4} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-grid"><label>Valor solicitado<input type="number" step="0.01" value={value} onChange={e=>setValue(e.target.value)}/></label><label>Entidad relacionada<input value={entityType} onChange={e=>setEntityType(e.target.value)} placeholder="order, purchase…"/></label><label className="form-span-2">ID relacionado<input value={entityId} onChange={e=>setEntityId(e.target.value)} placeholder="UUID opcional"/></label></div>{error&&<div className="notice notice--error">{error}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button primary-button--auto">Enviar solicitud</button></div></form></Shell>}
function DecisionModal({request,userId,close,done}:{request:Approval;userId:string;close:()=>void;done:()=>void}){const [notes,setNotes]=useState(''),[error,setError]=useState<string|null>(null);async function decide(status:'approved'|'rejected'){if(!supabase)return;const {error}=await supabase.from('approval_requests').update({status,authorized_by:userId,decision_notes:notes.trim()||null,decided_at:new Date().toISOString()}).eq('id',request.id).eq('status','pending');if(error)setError(error.message);else done()}return <Shell title={labels[request.request_type]||'Solicitud'} close={close}><div className="detail-notes"><p>{request.reason}</p>{request.requested_value!=null&&<strong>{money.format(Number(request.requested_value))}</strong>}</div><label>Notas de decisión<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<div className="form-actions"><button className="secondary-button" onClick={()=>void decide('rejected')}><XCircle size={16}/>Rechazar</button><button className="primary-button primary-button--auto" onClick={()=>void decide('approved')}><CheckCircle2 size={16}/>Aprobar</button></div></Shell>}
