import { FormEvent,useEffect,useMemo,useState } from 'react'
import { Building2, MapPin, Pencil, Plus } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Branch={id:string;name:string;address:string|null;active:boolean}
type Area={id:string;branch_id:string;name:string;active:boolean}
type Location={id:string;branch_id:string;area_id:string|null;name:string;location_type:string|null;active:boolean}

export function AreasPage({businessId}:{businessId:string}){
 const[branches,setBranches]=useState<Branch[]>([]),[areas,setAreas]=useState<Area[]>([]),[locations,setLocations]=useState<Location[]>([]),[branchFilter,setBranchFilter]=useState('all'),[open,setOpen]=useState(false),[editing,setEditing]=useState<Area|null>(null),[error,setError]=useState<string|null>(null)
 async function load(){if(!supabase)return;setError(null);const[b,a,l]=await Promise.all([supabase.from('branches').select('id,name,address,active').eq('business_id',businessId).order('name'),supabase.from('areas').select('id,branch_id,name,active').eq('business_id',businessId).order('name'),supabase.from('locations').select('id,branch_id,area_id,name,location_type,active').eq('business_id',businessId).order('name')]);const first=[b.error,a.error,l.error].find(Boolean);if(first)setError(first?.message??'No se pudieron cargar las áreas');setBranches((b.data??[]) as Branch[]);setAreas((a.data??[]) as Area[]);setLocations((l.data??[]) as Location[])}
 useEffect(()=>{void load()},[businessId])
 const filtered=useMemo(()=>branchFilter==='all'?areas:areas.filter(a=>a.branch_id===branchFilter),[areas,branchFilter])
 async function toggle(area:Area){if(!supabase)return;const{error}=await supabase.from('areas').update({active:!area.active,updated_at:new Date().toISOString()}).eq('id',area.id).eq('business_id',businessId);if(error)setError(error.message);else void load()}
 return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Estructura del negocio</span><h1>Áreas por sucursal</h1><p>Organiza producción, atención, almacén u otras áreas y relaciónalas con las ubicaciones físicas.</p></div><button className="primary-button primary-button--auto" onClick={()=>{setEditing(null);setOpen(true)}} disabled={branches.length===0}><Plus size={17}/>Nueva área</button></div>{error&&<div className="notice notice--error">{error}</div>}{branches.length===0&&<div className="notice">Primero crea una sucursal desde Configuración.</div>}<div className="toolbar"><label>Sucursal<select value={branchFilter} onChange={e=>setBranchFilter(e.target.value)}><option value="all">Todas</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><span className="toolbar__count">{filtered.length} área{filtered.length===1?'':'s'}</span></div><div className="data-card"><div className="data-list">{filtered.length===0?<div className="empty-state"><Building2 size={26}/><strong>Sin áreas</strong><span>Crea la primera para esta sucursal.</span></div>:filtered.map(a=>{const branch=branches.find(b=>b.id===a.branch_id);const locs=locations.filter(l=>l.area_id===a.id);return <div className="data-row" key={a.id}><div className="data-row__avatar"><Building2 size={18}/></div><div className="data-row__main"><strong>{a.name}</strong><span>{branch?.name??'Sucursal'} · {locs.length} ubicación{locs.length===1?'':'es'}</span>{locs.length>0&&<span>{locs.slice(0,3).map(l=>l.name).join(' · ')}{locs.length>3?'…':''}</span>}</div><div className="data-row__meta"><span className={`badge ${a.active?'badge--success':''}`}>{a.active?'Activa':'Inactiva'}</span><button className="mini-action" onClick={()=>{setEditing(a);setOpen(true)}}><Pencil size={14}/>Editar</button><button className="mini-action" onClick={()=>void toggle(a)}>{a.active?'Desactivar':'Activar'}</button></div></div>})}</div></div><div className="section-heading"><div><span className="eyebrow">Ubicaciones sin área</span><h2>Pendientes de clasificar</h2></div></div><div className="data-card"><div className="data-list">{locations.filter(l=>!l.area_id).length===0?<div className="empty-state"><MapPin size={26}/><strong>Todas las ubicaciones están clasificadas</strong></div>:locations.filter(l=>!l.area_id).map(l=><div className="data-row" key={l.id}><div className="data-row__avatar"><MapPin size={18}/></div><div className="data-row__main"><strong>{l.name}</strong><span>{branches.find(b=>b.id===l.branch_id)?.name??'Sucursal'} · {l.location_type??'sin tipo'}</span></div></div>)}</div></div>{open&&<AreaForm businessId={businessId} branches={branches} area={editing} close={()=>setOpen(false)} done={()=>{setOpen(false);void load()}}/>}</>}

function AreaForm({businessId,branches,area,close,done}:{businessId:string;branches:Branch[];area:Area|null;close:()=>void;done:()=>void}){const[f,setF]=useState({branch_id:area?.branch_id??branches[0]?.id??'',name:area?.name??'',active:area?.active??true}),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const payload={business_id:businessId,branch_id:f.branch_id,name:f.name.trim(),active:f.active,updated_at:new Date().toISOString()};const q=area?supabase.from('areas').update(payload).eq('id',area.id).eq('business_id',businessId):supabase.from('areas').insert(payload);const{error}=await q;if(error)setError(error.message);else done()}return <div className="modal-backdrop"><section className="modal-card"><div className="modal-card__header"><h2>{area?'Editar área':'Nueva área'}</h2><button type="button" className="icon-button" onClick={close}>×</button></div><form className="entity-form" onSubmit={submit}><label>Sucursal<select required value={f.branch_id} onChange={e=>setF({...f,branch_id:e.target.value})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Nombre<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Ej. Producción, Mostrador, Almacén"/></label><label className="checkbox-field"><input type="checkbox" checked={f.active} onChange={e=>setF({...f,active:e.target.checked})}/> Área activa</label>{error&&<div className="notice notice--error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button">Guardar</button></div></form></section></div>}
