import { FormEvent,useEffect,useState } from 'react'
import { CircleDollarSign } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Row=Record<string,any>
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const n=(v:unknown)=>Number(v??0)||0
export function CashDayPanel({businessId,userId}:{businessId:string;userId:string}){
 const [accounts,setAccounts]=useState<Row[]>([]),[session,setSession]=useState<Row|null>(null),[account,setAccount]=useState(''),[opening,setOpening]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false)
 async function load(){if(!supabase)return;const[a,s]=await Promise.all([supabase.from('financial_account_balances').select('account_id,name,current_balance,account_type').eq('business_id',businessId).eq('account_type','cash').order('name'),supabase.from('cash_sessions').select('*').eq('business_id',businessId).eq('status','open').order('opened_at',{ascending:false}).limit(1).maybeSingle()]);setAccounts(a.data??[]);setSession(s.data??null);if(!account&&a.data?.[0])setAccount(a.data[0].account_id);if(a.error||s.error)setError(a.error?.message??s.error?.message??null)}
 useEffect(()=>{void load()},[businessId])
 async function openCash(e:FormEvent){e.preventDefault();if(!supabase||!account)return;setBusy(true);setError(null);const{error}=await supabase.from('cash_sessions').insert({business_id:businessId,account_id:account,responsible_user_id:userId,opening_amount:n(opening),status:'open'});setBusy(false);if(error)setError(error.message);else{setOpening('');await load()}}
 async function adjustment(){if(!supabase||!session)return;const raw=window.prompt('Monto de entrada o salida. Usa negativo para salida.');if(!raw)return;const reason=window.prompt('Motivo del movimiento')?.trim();if(!reason)return;const{error}=await supabase.from('cash_session_adjustments').insert({business_id:businessId,cash_session_id:session.id,amount:n(raw),reason,created_by:userId});if(error)setError(error.message);else await load()}
 async function closeCash(){if(!supabase||!session)return;const raw=window.prompt('¿Cuánto efectivo contaste físicamente al cerrar?');if(!raw)return;const counted=n(raw);if(!window.confirm(`Cerrar caja con ${money.format(counted)} contados?`))return;const{error}=await supabase.from('cash_sessions').update({status:'closed',actual_close_amount:counted,closed_at:new Date().toISOString()}).eq('id',session.id).eq('business_id',businessId);if(error)setError(error.message);else await load()}
 const cashAccount=session?accounts.find(a=>a.account_id===session.account_id):null
 return <section className="data-card" style={{marginBottom:16}}><div className="section-heading" style={{padding:'16px 16px 0'}}><div><span className="eyebrow">Caja del día</span><h2>{session?'Caja abierta':'Abrir caja'}</h2></div></div>{error&&<div className="notice notice--error">{error}</div>}{session?<div className="data-list"><div className="data-row"><div className="data-row__avatar"><CircleDollarSign size={18}/></div><div className="data-row__main"><strong>{cashAccount?.name??'Caja'}</strong><span>Abierta con {money.format(n(session.opening_amount))} · {new Date(session.opened_at).toLocaleString('es-MX')}</span></div><div className="data-row__meta"><strong>{money.format(n(cashAccount?.current_balance))}</strong><span>Saldo de cuenta</span></div></div><div className="modal-actions" style={{padding:16}}><button className="secondary-button" onClick={()=>void adjustment()}>Registrar entrada / salida</button><button className="primary-button" onClick={()=>void closeCash()}>Contar y cerrar caja</button></div></div>:accounts.length===0?<div className="empty-state"><strong>Primero crea una cuenta de efectivo</strong><span>En Cuentas, pulsa Nuevo y selecciona tipo Efectivo.</span></div>:<form className="entity-form" onSubmit={openCash} style={{padding:16}}><div className="form-grid"><label>Cuenta de caja<select value={account} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.name} · {money.format(n(a.current_balance))}</option>)}</select></label><label>Efectivo contado al abrir<input required type="number" step="0.01" min="0" value={opening} onChange={e=>setOpening(e.target.value)}/></label></div><button className="primary-button primary-button--auto" disabled={busy}>{busy?'Abriendo…':'Abrir caja'}</button></form>}</section>
}
