import { FormEvent, useEffect, useMemo, useState } from 'react'
import { BadgeDollarSign, ContactRound, FileText, Phone, Plus, ShieldCheck, Tags, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './finance-suppliers.css'

type PhoneRow={id:string;phone:string;label:string|null;is_primary:boolean}
type ContactRow={id:string;name:string;phone:string|null;email:string|null;notes:string|null}
type RoleRow={contact_id:string;role:string}
type TaxRow={id:string;tax_id:string|null;legal_name:string|null;fiscal_regime:string|null;postal_code:string|null;fiscal_address:string|null;active:boolean}
type TagRow={id:string;name:string}
type Assignment={tag_id:string}
type RuleRow={id:string;min_deposit_percent:number|string|null;credit_limit:number|string|null;exposure_limit:number|string|null;require_full_payment:boolean;block_credit:boolean;blocked:boolean;notes:string|null}
type Agreement={id:string;product_id:string;product_variant_id:string|null;special_price:number|string;review_date:string|null;active:boolean;products:{name:string}|null;product_variants:{name:string}|null}
type History={agreement_id:string;special_price:number|string;effective_at:string}
type Product={id:string;name:string}
type Variant={id:string;product_id:string;name:string}

type Modal='phone'|'contact'|'tax'|'rules'|'price'|null
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const num=(v:unknown)=>Number.isFinite(Number(v??0))?Number(v??0):0

export function CustomerAdvancedPanel({businessId,customerId}:{businessId:string;customerId:string}){
 const [phones,setPhones]=useState<PhoneRow[]>([]),[contacts,setContacts]=useState<ContactRow[]>([]),[roles,setRoles]=useState<RoleRow[]>([]),[tax,setTax]=useState<TaxRow[]>([]),[tags,setTags]=useState<TagRow[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[rule,setRule]=useState<RuleRow|null>(null),[agreements,setAgreements]=useState<Agreement[]>([]),[history,setHistory]=useState<History[]>([]),[products,setProducts]=useState<Product[]>([]),[variants,setVariants]=useState<Variant[]>([])
 const [modal,setModal]=useState<Modal>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true)
 async function load(){if(!supabase)return;setLoading(true);setError(null);const [p,c,r,t,tg,a,ru,ag,h,pr,v]=await Promise.all([
  supabase.from('customer_phones').select('id,phone,label,is_primary').eq('business_id',businessId).eq('customer_id',customerId).eq('active',true).order('is_primary',{ascending:false}),
  supabase.from('customer_contacts').select('id,name,phone,email,notes').eq('business_id',businessId).eq('customer_id',customerId).eq('active',true).order('created_at'),
  supabase.from('customer_contact_roles').select('contact_id,role').eq('business_id',businessId).eq('active',true),
  supabase.from('customer_tax_profiles').select('id,tax_id,legal_name,fiscal_regime,postal_code,fiscal_address,active').eq('business_id',businessId).eq('customer_id',customerId).eq('active',true).order('created_at',{ascending:false}),
  supabase.from('customer_tags').select('id,name').eq('business_id',businessId).eq('active',true).order('name'),
  supabase.from('customer_tag_assignments').select('tag_id').eq('business_id',businessId).eq('customer_id',customerId),
  supabase.from('customer_rules').select('id,min_deposit_percent,credit_limit,exposure_limit,require_full_payment,block_credit,blocked,notes').eq('business_id',businessId).eq('customer_id',customerId).maybeSingle(),
  supabase.from('customer_price_agreements').select('id,product_id,product_variant_id,special_price,review_date,active,products(name),product_variants(name)').eq('business_id',businessId).eq('customer_id',customerId).eq('active',true).order('created_at',{ascending:false}),
  supabase.from('customer_price_history').select('agreement_id,special_price,effective_at').eq('business_id',businessId).order('effective_at',{ascending:false}),
  supabase.from('products').select('id,name').eq('business_id',businessId).eq('active',true).is('deleted_at',null).order('name'),
  supabase.from('product_variants').select('id,product_id,name').eq('business_id',businessId).eq('active',true).order('name')]);
 const first=[p,c,r,t,tg,a,ru,ag,h,pr,v].find(x=>x.error);if(first?.error)setError(first.error.message);setPhones((p.data??[]) as PhoneRow[]);setContacts((c.data??[]) as ContactRow[]);setRoles((r.data??[]) as RoleRow[]);setTax((t.data??[]) as TaxRow[]);setTags((tg.data??[]) as TagRow[]);setAssignments((a.data??[]) as Assignment[]);setRule((ru.data??null) as RuleRow|null);setAgreements((ag.data??[]) as unknown as Agreement[]);setHistory((h.data??[]) as History[]);setProducts((pr.data??[]) as Product[]);setVariants((v.data??[]) as Variant[]);setLoading(false)}
 useEffect(()=>{void load()},[businessId,customerId])
 const assigned=new Set(assignments.map(a=>a.tag_id));
 async function toggleTag(tagId:string){if(!supabase)return;setError(null);const result=assigned.has(tagId)?await supabase.from('customer_tag_assignments').delete().eq('business_id',businessId).eq('customer_id',customerId).eq('tag_id',tagId):await supabase.from('customer_tag_assignments').insert({business_id:businessId,customer_id:customerId,tag_id:tagId});if(result.error)setError(result.error.message);else await load()}
 const roleText=(id:string)=>roles.filter(r=>r.contact_id===id).map(r=>r.role).join(', ')
 if(loading)return <section className="drawer-section"><div className="empty-state empty-state--compact">Cargando información avanzada…</div></section>
 return <>
  {error&&<div className="notice notice--error">{error}</div>}
  <section className="drawer-section"><div className="section-title-row"><h3><Phone size={17}/> Teléfonos</h3><button className="secondary-button secondary-button--small" onClick={()=>setModal('phone')}><Plus size={15}/>Agregar</button></div>{phones.length===0?<Empty text="Sin teléfonos adicionales."/>:<div className="line-items">{phones.map(x=><div className="line-item" key={x.id}><div><strong>{x.phone}</strong><span>{x.label||'Sin etiqueta'}</span></div><span>{x.is_primary?'Principal':''}</span></div>)}</div>}</section>
  <section className="drawer-section"><div className="section-title-row"><h3><ContactRound size={17}/> Contactos</h3><button className="secondary-button secondary-button--small" onClick={()=>setModal('contact')}><Plus size={15}/>Agregar</button></div>{contacts.length===0?<Empty text="Sin contactos adicionales."/>:<div className="line-items">{contacts.map(x=><div className="line-item" key={x.id}><div><strong>{x.name}</strong><span>{[x.phone,x.email].filter(Boolean).join(' · ')||'Sin teléfono/correo'}</span></div><span>{roleText(x.id)||'Sin rol'}</span></div>)}</div>}</section>
  <section className="drawer-section"><div className="section-title-row"><h3><Tags size={17}/> Etiquetas</h3></div><div className="tag-grid">{tags.map(tag=><button key={tag.id} className={`badge tag-button ${assigned.has(tag.id)?'badge--success':''}`} onClick={()=>void toggleTag(tag.id)}>{tag.name}</button>)}</div></section>
  <section className="drawer-section"><div className="section-title-row"><h3><ShieldCheck size={17}/> Reglas comerciales</h3><button className="secondary-button secondary-button--small" onClick={()=>setModal('rules')}>{rule?'Editar':'Configurar'}</button></div>{!rule?<Empty text="Sin reglas especiales; se aplican las reglas generales."/>:<div className="detail-stack"><Compact label="Anticipo mínimo" value={rule.min_deposit_percent==null?'—':`${num(rule.min_deposit_percent)}%`}/><Compact label="Límite de crédito" value={rule.credit_limit==null?'—':money.format(num(rule.credit_limit))}/><Compact label="Exposición máxima" value={rule.exposure_limit==null?'—':money.format(num(rule.exposure_limit))}/><Compact label="Condiciones" value={[rule.require_full_payment?'Pago total requerido':null,rule.block_credit?'Crédito bloqueado':null,rule.blocked?'Cliente bloqueado':null].filter(Boolean).join(' · ')||'Normales'}/></div>}</section>
  <section className="drawer-section"><div className="section-title-row"><h3><FileText size={17}/> Perfil fiscal</h3><button className="secondary-button secondary-button--small" onClick={()=>setModal('tax')}><Plus size={15}/>Agregar</button></div>{tax.length===0?<Empty text="Sin perfil fiscal adicional."/>:<div className="line-items">{tax.map(x=><div className="line-item" key={x.id}><div><strong>{x.legal_name||'Perfil fiscal'}</strong><span>{[x.tax_id,x.fiscal_regime,x.postal_code].filter(Boolean).join(' · ')||'Sin datos'}</span></div></div>)}</div>}</section>
  <section className="drawer-section"><div className="section-title-row"><h3><BadgeDollarSign size={17}/> Precios especiales</h3><button className="secondary-button secondary-button--small" onClick={()=>setModal('price')}><Plus size={15}/>Agregar</button></div>{agreements.length===0?<Empty text={products.length===0?'Primero crea productos para asignar precios especiales.':'Sin precios especiales.'}/>:<div className="line-items">{agreements.map(x=>{const entries=history.filter(h=>h.agreement_id===x.id);return <div className="line-item" key={x.id}><div><strong>{x.products?.name??'Producto'}{x.product_variants?.name?` · ${x.product_variants.name}`:''}</strong><span>{x.review_date?`Revisar ${x.review_date}`:'Sin fecha de revisión'} · {entries.length} registro(s) histórico(s)</span></div><strong>{money.format(num(x.special_price))}</strong></div>})}</div>}</section>
  {modal==='phone'&&<PhoneModal businessId={businessId} customerId={customerId} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
  {modal==='contact'&&<ContactModal businessId={businessId} customerId={customerId} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
  {modal==='tax'&&<TaxModal businessId={businessId} customerId={customerId} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
  {modal==='rules'&&<RulesModal businessId={businessId} customerId={customerId} current={rule} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
  {modal==='price'&&<PriceModal businessId={businessId} customerId={customerId} products={products} variants={variants} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 </>
}
function Empty({text}:{text:string}){return <div className="empty-state empty-state--compact">{text}</div>}
function Compact({label,value}:{label:string;value:string}){return <div className="detail-item"><div><span>{label}</span><strong>{value}</strong></div></div>}
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="form-modal form-modal--small"><div className="drawer-header"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={19}/></button></div>{children}</div></div>}
function Actions({close,saving=false}:{close:()=>void;saving?:boolean}){return <div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button primary-button--auto" disabled={saving}>{saving?'Guardando…':'Guardar'}</button></div>}
function PhoneModal({businessId,customerId,close,done}:{businessId:string;customerId:string;close:()=>void;done:()=>void}){const [phone,setPhone]=useState(''),[label,setLabel]=useState(''),[primary,setPrimary]=useState(false),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;if(primary)await supabase.from('customer_phones').update({is_primary:false}).eq('business_id',businessId).eq('customer_id',customerId);const {error}=await supabase.from('customer_phones').insert({business_id:businessId,customer_id:customerId,phone:phone.trim(),label:label.trim()||null,is_primary:primary});if(error)setError(error.message);else done()}return <Shell title="Agregar teléfono" close={close}><form className="entity-form" onSubmit={submit}><label>Teléfono<input required value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Etiqueta<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="WhatsApp, oficina, personal…"/></label><label className="checkbox-field"><input type="checkbox" checked={primary} onChange={e=>setPrimary(e.target.checked)}/> Teléfono principal</label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function ContactModal({businessId,customerId,close,done}:{businessId:string;customerId:string;close:()=>void;done:()=>void}){const [name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[roles,setRoles]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {data,error}=await supabase.from('customer_contacts').insert({business_id:businessId,customer_id:customerId,name:name.trim(),phone:phone.trim()||null,email:email.trim()||null,notes:notes.trim()||null}).select('id').single();if(error){setError(error.message);return}const roleList=roles.split(',').map(x=>x.trim()).filter(Boolean);if(roleList.length){const rr=await supabase.from('customer_contact_roles').insert(roleList.map(role=>({business_id:businessId,contact_id:data.id,role})));if(rr.error){setError(rr.error.message);return}}done()}return <Shell title="Agregar contacto" close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Roles<input value={roles} onChange={e=>setRoles(e.target.value)} placeholder="Pedidos, Pagos, Aprobación de diseño"/></label><label className="form-span-2">Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function TaxModal({businessId,customerId,close,done}:{businessId:string;customerId:string;close:()=>void;done:()=>void}){const [taxId,setTaxId]=useState(''),[legal,setLegal]=useState(''),[regime,setRegime]=useState(''),[postal,setPostal]=useState(''),[address,setAddress]=useState(''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('customer_tax_profiles').insert({business_id:businessId,customer_id:customerId,tax_id:taxId.trim()||null,legal_name:legal.trim()||null,fiscal_regime:regime.trim()||null,postal_code:postal.trim()||null,fiscal_address:address.trim()||null});if(error)setError(error.message);else done()}return <Shell title="Agregar perfil fiscal" close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>RFC / ID fiscal<input value={taxId} onChange={e=>setTaxId(e.target.value)}/></label><label>Razón social<input value={legal} onChange={e=>setLegal(e.target.value)}/></label><label>Régimen fiscal<input value={regime} onChange={e=>setRegime(e.target.value)}/></label><label>Código postal<input value={postal} onChange={e=>setPostal(e.target.value)}/></label><label className="form-span-2">Domicilio fiscal<input value={address} onChange={e=>setAddress(e.target.value)}/></label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function RulesModal({businessId,customerId,current,close,done}:{businessId:string;customerId:string;current:RuleRow|null;close:()=>void;done:()=>void}){const [deposit,setDeposit]=useState(current?.min_deposit_percent==null?'':String(current.min_deposit_percent)),[credit,setCredit]=useState(current?.credit_limit==null?'':String(current.credit_limit)),[exposure,setExposure]=useState(current?.exposure_limit==null?'':String(current.exposure_limit)),[full,setFull]=useState(current?.require_full_payment??false),[blockCredit,setBlockCredit]=useState(current?.block_credit??false),[blocked,setBlocked]=useState(current?.blocked??false),[notes,setNotes]=useState(current?.notes??''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const payload={business_id:businessId,customer_id:customerId,min_deposit_percent:deposit===''?null:num(deposit),credit_limit:credit===''?null:num(credit),exposure_limit:exposure===''?null:num(exposure),require_full_payment:full,block_credit:blockCredit,blocked,notes:notes.trim()||null,updated_at:new Date().toISOString()};const result=current?await supabase.from('customer_rules').update(payload).eq('id',current.id):await supabase.from('customer_rules').insert(payload);if(result.error)setError(result.error.message);else done()}return <Shell title="Reglas del cliente" close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Anticipo mínimo %<input type="number" min="0" max="100" step="0.01" value={deposit} onChange={e=>setDeposit(e.target.value)}/></label><label>Límite de crédito<input type="number" min="0" step="0.01" value={credit} onChange={e=>setCredit(e.target.value)}/></label><label>Exposición máxima<input type="number" min="0" step="0.01" value={exposure} onChange={e=>setExposure(e.target.value)}/></label></div><label className="checkbox-field"><input type="checkbox" checked={full} onChange={e=>setFull(e.target.checked)}/> Requerir pago total</label><label className="checkbox-field"><input type="checkbox" checked={blockCredit} onChange={e=>setBlockCredit(e.target.checked)}/> Bloquear crédito</label><label className="checkbox-field"><input type="checkbox" checked={blocked} onChange={e=>setBlocked(e.target.checked)}/> Bloquear cliente</label><label>Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function PriceModal({businessId,customerId,products,variants,close,done}:{businessId:string;customerId:string;products:Product[];variants:Variant[];close:()=>void;done:()=>void}){const [product,setProduct]=useState(''),[variant,setVariant]=useState(''),[price,setPrice]=useState(''),[review,setReview]=useState(''),[error,setError]=useState<string|null>(null);const available=useMemo(()=>variants.filter(v=>v.product_id===product),[variants,product]);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('customer_price_agreements').insert({business_id:businessId,customer_id:customerId,product_id:product,product_variant_id:variant||null,special_price:num(price),review_date:review||null});if(error)setError(error.message);else done()}return <Shell title="Precio especial" close={close}><form className="entity-form" onSubmit={submit}>{products.length===0?<div className="notice">No hay productos activos. Crea productos antes de definir un precio especial.</div>:<><label>Producto<select required value={product} onChange={e=>{setProduct(e.target.value);setVariant('')}}><option value="">Selecciona</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Variante<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="">Todas / sin variante</option>{available.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="form-grid"><label>Precio especial<input required type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Fecha de revisión<input type="date" value={review} onChange={e=>setReview(e.target.value)}/></label></div></>}{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
