import { useEffect,useState } from 'react'
import { CreditCard, ReceiptText } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Summary={order_value:number|string;confirmed_payments:number|string;balance_due:number|string;bad_debt_remaining:number|string}
type Order={id:string;folio:string;status:string;total:number|string;promised_at:string|null;created_at:string}
type Payment={id:string;amount:number|string;status:string;reported_at:string;reference:string|null}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});const n=(v:unknown)=>Number(v??0)||0
export function CustomerFinancialPanel({businessId,customerId}:{businessId:string;customerId:string}){const[summary,setSummary]=useState<Summary|null>(null),[orders,setOrders]=useState<Order[]>([]),[payments,setPayments]=useState<Payment[]>([]),[error,setError]=useState<string|null>(null);useEffect(()=>{if(!supabase)return;void(async()=>{const[s,o,p]=await Promise.all([supabase.from('customer_financial_summary').select('order_value,confirmed_payments,balance_due,bad_debt_remaining').eq('business_id',businessId).eq('customer_id',customerId).maybeSingle(),supabase.from('orders').select('id,folio,status,total,promised_at,created_at').eq('business_id',businessId).eq('customer_id',customerId).is('deleted_at',null).order('created_at',{ascending:false}).limit(5),supabase.from('payments').select('id,amount,status,reported_at,reference').eq('business_id',businessId).eq('customer_id',customerId).order('reported_at',{ascending:false}).limit(5)]);const first=[s.error,o.error,p.error].find(Boolean);if(first)setError(first?.message??'No se pudo cargar el resumen financiero');setSummary((s.data??null) as Summary|null);setOrders((o.data??[]) as Order[]);setPayments((p.data??[]) as Payment[])})()},[businessId,customerId]);return <section className="advanced-panel"><div className="section-heading"><div><span className="eyebrow">Finanzas del cliente</span><h3>Resumen financiero</h3></div></div>{error&&<div className="notice notice--error">{error}</div>}<div className="order-summary-grid"><div><span>Valor de pedidos</span><strong>{money.format(n(summary?.order_value))}</strong></div><div><span>Pagos confirmados</span><strong>{money.format(n(summary?.confirmed_payments))}</strong></div><div><span>Saldo por cobrar</span><strong>{money.format(n(summary?.balance_due))}</strong></div><div><span>Incobrable pendiente</span><strong>{money.format(n(summary?.bad_debt_remaining))}</strong></div></div><div className="section-heading"><div><span className="eyebrow">Actividad reciente</span><h4>Pedidos</h4></div></div>{orders.length===0?<div className="empty-state empty-state--compact">Sin pedidos recientes.</div>:orders.map(o=><div className="balance-row" key={o.id}><span><ReceiptText size={14}/> {o.folio} · {o.status}</span><strong>{money.format(n(o.total))}</strong></div>)}<div className="section-heading"><div><span className="eyebrow">Cobros recientes</span><h4>Pagos</h4></div></div>{payments.length===0?<div className="empty-state empty-state--compact">Sin pagos recientes.</div>:payments.map(p=><div className="balance-row" key={p.id}><span><CreditCard size={14}/> {new Date(p.reported_at).toLocaleDateString('es-MX')} · {p.status}{p.reference?` · ${p.reference}`:''}</span><strong>{money.format(n(p.amount))}</strong></div>)}</section>}
