import { FormEvent, useEffect, useMemo, useState } from 'react'
import { CircleDollarSign, Plus, Search, WalletCards, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './finance-suppliers.css'

type Account={account_id:string;business_id:string;name:string;account_type:string;currency:string;opening_balance:number|string|null;movement_total:number|string|null;current_balance:number|string|null}
type Customer={id:string;name:string}
type Order={id:string;folio:string|null;customer_id:string|null}
type Method={id:string;name:string;method_type:string}
type Payment={id:string;customer_id:string;order_id:string|null;account_id:string|null;payment_method_id:string|null;amount:number|string;payment_type:string;status:string;reported_at:string;reference:string|null;customers:{name:string}|null;orders:{folio:string|null}|null}
type Expense={id:string;category:string;account_id:string|null;amount:number|string;business_amount:number|string;personal_amount:number|string;expense_date:string;status:string;notes:string|null}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const num=(v:unknown)=>Number.isFinite(Number(v??0))?Number(v??0):0

export function FinancePage({businessId,userId}:{businessId:string;userId:string}){
 const [accounts,setAccounts]=useState<Account[]>([]),[payments,setPayments]=useState<Payment[]>([]),[expenses,setExpenses]=useState<Expense[]>([])
 const [customers,setCustomers]=useState<Customer[]>([]),[orders,setOrders]=useState<Order[]>([]),[methods,setMethods]=useState<Method[]>([])
 const [tab,setTab]=useState<'accounts'|'payments'|'expenses'>('accounts'),[query,setQuery]=useState(''),[modal,setModal]=useState<'account'|'payment'|'expense'|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true)
 async function load(){if(!supabase)return;setLoading(true);setError(null);const [a,p,e,c,o,m]=await Promise.all([
  supabase.from('financial_account_balances').select('*').eq('business_id',businessId).order('name'),
  supabase.from('payments').select('id,customer_id,order_id,account_id,payment_method_id,amount,payment_type,status,reported_at,reference,customers(name),orders(folio)').eq('business_id',businessId).order('reported_at',{ascending:false}).limit(100),
  supabase.from('expenses').select('id,category,account_id,amount,business_amount,personal_amount,expense_date,status,notes').eq('business_id',businessId).order('expense_date',{ascending:false}).limit(100),
  supabase.from('customers').select('id,name').eq('business_id',businessId).is('deleted_at',null).eq('active',true).order('name'),
  supabase.from('orders').select('id,folio,customer_id').eq('business_id',businessId).is('deleted_at',null).order('created_at',{ascending:false}).limit(200),
  supabase.from('payment_methods').select('id,name,method_type').eq('business_id',businessId).eq('active',true).order('name')]);
  const first=[a,p,e,c,o,m].find(r=>r.error);if(first?.error)setError(first.error.message);setAccounts((a.data??[]) as Account[]);setPayments((p.data??[]) as unknown as Payment[]);setExpenses((e.data??[]) as Expense[]);setCustomers((c.data??[]) as Customer[]);setOrders((o.data??[]) as Order[]);setMethods((m.data??[]) as Method[]);setLoading(false)}
 useEffect(()=>{void load()},[businessId])
 const q=query.trim().toLowerCase();const visible=useMemo(()=>tab==='accounts'?accounts.filter(x=>!q||x.name.toLowerCase().includes(q)):tab==='payments'?payments.filter(x=>!q||x.customers?.name?.toLowerCase().includes(q)||x.orders?.folio?.toLowerCase().includes(q)||x.reference?.toLowerCase().includes(q)):expenses.filter(x=>!q||x.category.toLowerCase().includes(q)||x.notes?.toLowerCase().includes(q)),[tab,accounts,payments,expenses,q])
 async function confirmPayment(id:string){if(!supabase)return;const {error}=await supabase.from('payments').update({status:'confirmed',confirmed_at:new Date().toISOString(),confirmed_by:userId}).eq('id',id).eq('business_id',businessId);if(error)setError(error.message);else await load()}
 async function payExpense(id:string){if(!supabase)return;const {error}=await supabase.from('expenses').update({status:'paid'}).eq('id',id).eq('business_id',businessId);if(error)setError(error.message);else await load()}
 return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Control financiero</span><h1>Finanzas</h1><p>Cuentas, cobros y gastos conectados al libro de movimientos.</p></div><button className="primary-button primary-button--auto" onClick={()=>setModal(tab==='accounts'?'account':tab==='payments'?'payment':'expense')}><Plus size={17}/>Nuevo</button></div>
 <div className="module-tabs"><button className={tab==='accounts'?'active':''} onClick={()=>setTab('accounts')}>Cuentas</button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}>Pagos</button><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>Gastos</button></div>
 <div className="toolbar"><div className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar…"/></div><span className="toolbar__count">{visible.length} registros</span></div>{error&&<div className="notice notice--error">{error}</div>}
 <div className="data-card"><div className="data-list">{loading?<div className="empty-state">Cargando…</div>:visible.length===0?<div className="empty-state"><WalletCards size={28}/><strong>Sin registros</strong></div>:tab==='accounts'?(visible as Account[]).map(a=><div className="data-row finance-row" key={a.account_id}><div className="data-row__avatar"><WalletCards size={18}/></div><div className="data-row__main"><strong>{a.name}</strong><span>{a.account_type} · {a.currency}</span></div><div className="data-row__meta"><strong>{money.format(num(a.current_balance))}</strong><span>Saldo actual</span></div></div>):tab==='payments'?(visible as Payment[]).map(p=><div className="data-row finance-row" key={p.id}><div className="data-row__avatar"><CircleDollarSign size={18}/></div><div className="data-row__main"><strong>{p.customers?.name??'Cliente'}</strong><span>{p.orders?.folio??'Sin pedido'} · {p.payment_type}</span></div><div className="data-row__meta"><strong>{money.format(num(p.amount))}</strong><span className="badge">{p.status}</span>{p.status!=='confirmed'&&p.status!=='cancelled'&&<button className="mini-action" onClick={()=>void confirmPayment(p.id)}>Confirmar</button>}</div></div>):(visible as Expense[]).map(e=><div className="data-row finance-row" key={e.id}><div className="data-row__avatar"><CircleDollarSign size={18}/></div><div className="data-row__main"><strong>{e.category}</strong><span>{e.expense_date} · negocio {money.format(num(e.business_amount))}</span></div><div className="data-row__meta"><strong>{money.format(num(e.amount))}</strong><span className="badge">{e.status}</span>{e.status==='recorded'&&<button className="mini-action" onClick={()=>void payExpense(e.id)}>Marcar pagado</button>}</div></div>)}</div></div>
 {modal==='account'&&<AccountModal businessId={businessId} userId={userId} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 {modal==='payment'&&<PaymentModal businessId={businessId} userId={userId} accounts={accounts} customers={customers} orders={orders} methods={methods} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 {modal==='expense'&&<ExpenseModal businessId={businessId} userId={userId} accounts={accounts} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}</>}

function AccountModal({businessId,close,done}:{businessId:string;userId:string;close:()=>void;done:()=>void}){const [name,setName]=useState(''),[type,setType]=useState('cash'),[opening,setOpening]=useState('0'),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('financial_accounts').insert({business_id:businessId,name,account_type:type,opening_balance:num(opening)});if(error)setError(error.message);else done()}return <Modal title="Nueva cuenta" close={close}><form className="entity-form" onSubmit={submit}><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="cash">Efectivo</option><option value="bank">Banco</option><option value="mercado_pago">Mercado Pago</option><option value="personal_business_use">Personal usada por negocio</option><option value="other">Otra</option></select></label><label>Saldo inicial<input type="number" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Modal>}
function PaymentModal({businessId,userId,accounts,customers,orders,methods,close,done}:{businessId:string;userId:string;accounts:Account[];customers:Customer[];orders:Order[];methods:Method[];close:()=>void;done:()=>void}){const [customer,setCustomer]=useState(''),[order,setOrder]=useState(''),[account,setAccount]=useState(''),[method,setMethod]=useState(''),[amount,setAmount]=useState(''),[type,setType]=useState('payment'),[reference,setReference]=useState(''),[error,setError]=useState<string|null>(null);const filteredOrders=orders.filter(o=>!customer||o.customer_id===customer);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('payments').insert({business_id:businessId,customer_id:customer,order_id:order||null,account_id:account||null,payment_method_id:method||null,amount:num(amount),payment_type:type,status:'reported',reference:reference||null,created_by:userId});if(error)setError(error.message);else done()}return <Modal title="Registrar pago" close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Cliente<select required value={customer} onChange={e=>{setCustomer(e.target.value);setOrder('')}}><option value="">Selecciona</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Pedido<select value={order} onChange={e=>setOrder(e.target.value)}><option value="">Sin pedido</option>{filteredOrders.map(o=><option key={o.id} value={o.id}>{o.folio??o.id.slice(0,8)}</option>)}</select></label><label>Cuenta destino<select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Pendiente</option>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.name}</option>)}</select></label><label>Método<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">Sin método</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Monto<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="payment">Pago</option><option value="deposit">Anticipo</option><option value="installment">Abono</option></select></label><label className="form-span-2">Referencia<input value={reference} onChange={e=>setReference(e.target.value)}/></label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Modal>}
function ExpenseModal({businessId,userId,accounts,close,done}:{businessId:string;userId:string;accounts:Account[];close:()=>void;done:()=>void}){const [category,setCategory]=useState(''),[account,setAccount]=useState(''),[amount,setAmount]=useState(''),[personal,setPersonal]=useState('0'),[notes,setNotes]=useState(''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const total=num(amount),personalAmount=num(personal),businessAmount=Math.max(0,total-personalAmount);const {error}=await supabase.from('expenses').insert({business_id:businessId,category,account_id:account||null,amount:total,business_amount:businessAmount,personal_amount:personalAmount,status:'recorded',notes:notes||null,created_by:userId});if(error)setError(error.message);else done()}return <Modal title="Registrar gasto" close={close}><form className="entity-form" onSubmit={submit}><label>Categoría<input required value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Cuenta<select value={account} onChange={e=>setAccount(e.target.value)}><option value="">Aún no pagado</option>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.name}</option>)}</select></label><div className="form-grid"><label>Monto total<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Parte personal<input type="number" min="0" step="0.01" value={personal} onChange={e=>setPersonal(e.target.value)}/></label></div><label>Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="form-modal form-modal--small"><div className="drawer-header"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={19}/></button></div>{children}</div></div>}
function Actions({close}:{close:()=>void}){return <div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button primary-button--auto">Guardar</button></div>}
