import { FormEvent, useEffect, useState } from 'react'
import { Plus, RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Account={account_id:string;name:string;current_balance:number|string|null}
type Customer={id:string;name:string}
type Row=Record<string,any>
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const n=(v:unknown)=>Number(v??0)||0
const today=()=>new Date().toISOString().slice(0,10)

type Tab='transfers'|'reconcile'|'refunds'|'plans'|'funds'|'debts'|'assets'|'goals'
const labels:Record<Tab,string>={transfers:'Transferencias',reconcile:'Conciliación',refunds:'Reembolsos',plans:'Planes de pago',funds:'Fondos',debts:'Deudas',assets:'Activos',goals:'Metas'}

export function FinanceAdvancedPage({businessId,userId}:{businessId:string;userId:string}){
 const [tab,setTab]=useState<Tab>('transfers'),[rows,setRows]=useState<Row[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false)
 async function load(){if(!supabase)return;setLoading(true);setError(null);const table:Record<Tab,string>={transfers:'account_transfers',reconcile:'account_reconciliations',refunds:'refunds',plans:'payment_plans',funds:'business_funds',debts:'business_debts',assets:'assets',goals:'financial_goals'};const [r,a,c]=await Promise.all([supabase.from(table[tab]).select('*').eq('business_id',businessId).order('created_at',{ascending:false}).limit(100),supabase.from('financial_account_balances').select('account_id,name,current_balance').eq('business_id',businessId).order('name'),supabase.from('customers').select('id,name').eq('business_id',businessId).eq('active',true).is('deleted_at',null).order('name')]);if(r.error)setError(r.error.message);setRows(r.data??[]);setAccounts((a.data??[]) as Account[]);setCustomers((c.data??[]) as Customer[]);setLoading(false)}
 useEffect(()=>{void load()},[businessId,tab])
 async function completeTransfer(row:Row){if(!supabase)return;const {error}=await supabase.from('account_transfers').update({status:'completed',transferred_at:new Date().toISOString()}).eq('id',row.id).eq('business_id',businessId);if(error)setError(error.message);else void load()}
 async function reconcile(row:Row){if(!supabase)return;const {error}=await supabase.from('account_reconciliations').update({status:'reconciled',reconciled_by:userId,reconciled_at:new Date().toISOString()}).eq('id',row.id).eq('business_id',businessId);if(error)setError(error.message);else void load()}
 return <>
  <div className="page-heading page-heading--actions"><div><span className="eyebrow">Control financiero</span><h1>Finanzas avanzadas</h1><p>Transferencias, conciliaciones, reembolsos, crédito, fondos, activos, deudas y metas.</p></div><button className="primary-button primary-button--auto" onClick={()=>setOpen(true)}><Plus size={17}/>Nuevo</button></div>
  <div className="module-tabs">{(Object.keys(labels) as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{labels[t]}</button>)}</div>
  {error&&<div className="notice notice--error">{error}</div>}
  <div className="data-card"><div className="data-list">{loading?<div className="empty-state">Cargando…</div>:rows.length===0?<div className="empty-state"><strong>Sin registros</strong><span>Crea el primer registro de {labels[tab].toLowerCase()}.</span></div>:rows.map(r=><div className="data-row" key={r.id}><div className="data-row__main"><strong>{title(tab,r,customers)}</strong><span>{detail(tab,r,accounts)}</span></div><div className="data-row__meta"><strong>{amount(tab,r)}</strong><span className="badge">{r.status??(r.active===false?'inactivo':'activo')}</span>{tab==='transfers'&&r.status==='pending'&&<button className="mini-action" onClick={()=>void completeTransfer(r)}>Completar</button>}{tab==='reconcile'&&r.status==='pending'&&<button className="mini-action" onClick={()=>void reconcile(r)}>Conciliar</button>}</div></div>)}</div></div>
  {open&&<CreateModal tab={tab} businessId={businessId} userId={userId} accounts={accounts} customers={customers} close={()=>setOpen(false)} done={()=>{setOpen(false);void load()}}/>}
 </>
}
function title(tab:Tab,r:Row,customers:Customer[]){if(tab==='transfers')return 'Transferencia entre cuentas';if(tab==='reconcile')return 'Conciliación '+r.reconciliation_date;if(tab==='refunds')return 'Reembolso · '+(customers.find(c=>c.id===r.customer_id)?.name??'Cliente');if(tab==='plans')return 'Plan · '+(customers.find(c=>c.id===r.customer_id)?.name??'Cliente');return r.name??({funds:'Fondo',debts:'Deuda',assets:'Activo',goals:'Meta'} as any)[tab]??labels[tab]}
function detail(tab:Tab,r:Row,accounts:Account[]){const an=(id:string)=>accounts.find(a=>a.account_id===id)?.name??'Cuenta';if(tab==='transfers')return `${an(r.source_account_id)} → ${an(r.destination_account_id)} · comisión ${money.format(n(r.fee))}`;if(tab==='reconcile')return `Sistema ${money.format(n(r.system_balance))} · real ${money.format(n(r.actual_balance))} · diferencia ${money.format(n(r.difference))}`;if(tab==='refunds')return `${r.refund_type} · ${r.reason}`;if(tab==='plans')return `${r.installment_count} parcialidades · inicia ${r.start_date}`;if(tab==='funds')return `Meta ${r.target_amount==null?'sin monto':money.format(n(r.target_amount))}`;if(tab==='debts')return `Saldo ${money.format(n(r.current_balance))} · próximo ${r.next_payment_date??'sin fecha'}`;if(tab==='assets')return `${r.status} · compra ${r.purchase_date??'sin fecha'}`;return `${r.goal_type} · ${r.period_start} → ${r.period_end}`}
function amount(tab:Tab,r:Row){const v=tab==='transfers'?r.amount:tab==='refunds'?r.amount:tab==='plans'?r.total_amount:tab==='funds'?r.target_amount:tab==='debts'?r.current_balance:tab==='assets'?r.purchase_cost:tab==='goals'?r.target_amount:null;return v==null?'':money.format(n(v))}

function CreateModal({tab,businessId,userId,accounts,customers,close,done}:{tab:Tab;businessId:string;userId:string;accounts:Account[];customers:Customer[];close:()=>void;done:()=>void}){
 const [f,setF]=useState<Record<string,string>>({date:today(),start:today(),end:today(),type:'partial',status:'active',count:'1'}),[error,setError]=useState<string|null>(null)
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;let table='',payload:Row={business_id:businessId};
  if(tab==='transfers'){table='account_transfers';payload={...payload,source_account_id:f.source,destination_account_id:f.dest,amount:n(f.amount),fee:n(f.fee),status:'pending',notes:f.notes||null,created_by:userId}}
  if(tab==='reconcile'){table='account_reconciliations';payload={...payload,account_id:f.account,reconciliation_date:f.date,system_balance:0,actual_balance:n(f.amount),status:'pending',notes:f.notes||null}}
  if(tab==='refunds'){table='refunds';payload={...payload,customer_id:f.customer,account_id:f.account||null,refund_type:f.type||'partial',amount:n(f.amount),reason:f.notes||'Reembolso',status:'pending',created_by:userId}}
  if(tab==='plans'){table='payment_plans';payload={...payload,customer_id:f.customer,total_amount:n(f.amount),installment_count:n(f.count),start_date:f.start,status:'active',notes:f.notes||null,created_by:userId}}
  if(tab==='funds'){table='business_funds';payload={...payload,name:f.name,target_amount:f.amount?n(f.amount):null,target_date:f.end||null,active:true,notes:f.notes||null}}
  if(tab==='debts'){table='business_debts';payload={...payload,name:f.name,initial_principal:n(f.amount),current_balance:n(f.amount),interest_rate:f.rate?n(f.rate):null,scheduled_payment:f.payment?n(f.payment):null,next_payment_date:f.end||null,status:'active',notes:f.notes||null}}
  if(tab==='assets'){table='assets';payload={...payload,name:f.name,purchase_date:f.date,purchase_cost:f.amount?n(f.amount):null,status:'active',active:true,notes:f.notes||null}}
  if(tab==='goals'){table='financial_goals';payload={...payload,goal_type:f.type||'sales',period_type:'custom',target_amount:n(f.amount),period_start:f.start,period_end:f.end,active:true,notes:f.notes||null}}
  const {error}=await supabase.from(table).insert(payload);if(error)setError(error.message);else done()}
 const accountSelect=(key:string,label:string)=><label>{label}<select required value={f[key]??''} onChange={e=>set(key,e.target.value)}><option value="">Selecciona</option>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.name} · {money.format(n(a.current_balance))}</option>)}</select></label>
 return <div className="modal-backdrop"><section className="modal-card"><div className="modal-card__header"><div><span className="eyebrow">Finanzas</span><h2>Nuevo · {labels[tab]}</h2></div><button className="icon-button" onClick={close}>×</button></div><form className="entity-form" onSubmit={submit}>
  {tab==='transfers'&&<>{accountSelect('source','Cuenta origen')}{accountSelect('dest','Cuenta destino')}<label>Monto<input required type="number" min="0.01" step="0.01" onChange={e=>set('amount',e.target.value)}/></label><label>Comisión<input type="number" min="0" step="0.01" defaultValue="0" onChange={e=>set('fee',e.target.value)}/></label></>}
  {tab==='reconcile'&&<>{accountSelect('account','Cuenta')}<label>Fecha<input type="date" value={f.date} onChange={e=>set('date',e.target.value)}/></label><label>Saldo real<input required type="number" step="0.01" onChange={e=>set('amount',e.target.value)}/></label></>}
  {(tab==='refunds'||tab==='plans')&&<label>Cliente<select required value={f.customer??''} onChange={e=>set('customer',e.target.value)}><option value="">Selecciona</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
  {tab==='refunds'&&<>{accountSelect('account','Cuenta de salida')}<label>Tipo<select value={f.type} onChange={e=>set('type',e.target.value)}><option value="partial">Parcial</option><option value="full">Total</option><option value="store_credit">Crédito a favor</option></select></label><label>Monto<input required type="number" min="0.01" step="0.01" onChange={e=>set('amount',e.target.value)}/></label></>}
  {tab==='plans'&&<><label>Total<input required type="number" min="0.01" step="0.01" onChange={e=>set('amount',e.target.value)}/></label><label>Parcialidades<input required type="number" min="1" value={f.count} onChange={e=>set('count',e.target.value)}/></label><label>Inicio<input type="date" value={f.start} onChange={e=>set('start',e.target.value)}/></label></>}
  {(tab==='funds'||tab==='debts'||tab==='assets')&&<label>Nombre<input required onChange={e=>set('name',e.target.value)}/></label>}
  {tab==='funds'&&<><label>Meta de fondo<input type="number" min="0" step="0.01" onChange={e=>set('amount',e.target.value)}/></label><label>Fecha meta<input type="date" onChange={e=>set('end',e.target.value)}/></label></>}
  {tab==='debts'&&<><label>Principal inicial<input required type="number" min="0.01" step="0.01" onChange={e=>set('amount',e.target.value)}/></label><label>Tasa de interés<input type="number" min="0" step="0.0001" onChange={e=>set('rate',e.target.value)}/></label><label>Pago programado<input type="number" min="0" step="0.01" onChange={e=>set('payment',e.target.value)}/></label><label>Próxima fecha<input type="date" onChange={e=>set('end',e.target.value)}/></label></>}
  {tab==='assets'&&<><label>Fecha de compra<input type="date" value={f.date} onChange={e=>set('date',e.target.value)}/></label><label>Costo<input type="number" min="0" step="0.01" onChange={e=>set('amount',e.target.value)}/></label></>}
  {tab==='goals'&&<><label>Tipo<select value={f.type} onChange={e=>set('type',e.target.value)}><option value="sales">Ventas</option><option value="profit">Utilidad</option><option value="expenses">Gastos</option><option value="additional_profit">Utilidad adicional</option><option value="cash_reserve">Reserva de efectivo</option></select></label><label>Meta<input required type="number" min="0" step="0.01" onChange={e=>set('amount',e.target.value)}/></label><label>Inicio<input type="date" value={f.start} onChange={e=>set('start',e.target.value)}/></label><label>Fin<input type="date" value={f.end} onChange={e=>set('end',e.target.value)}/></label></>}
  <label>Notas<textarea rows={3} onChange={e=>set('notes',e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button">Guardar</button></div>
 </form></section></div>
}
