import { FormEvent, useEffect, useState } from 'react'
import { Plus } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Row=Record<string,any>; type Tab='badDebts'|'recurring'|'allocations'|'periods'|'audit'
const labels:Record<Tab,string>={badDebts:'Incobrables',recurring:'Gastos recurrentes',allocations:'Gastos por pedido',periods:'Cierres mensuales',audit:'Auditoría'}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}); const n=(v:unknown)=>Number(v??0)||0
const today=()=>new Date().toISOString().slice(0,10)
const frequencyLabel=(v:string)=>({daily:'Diario',diario:'Diario',weekly:'Semanal',semanal:'Semanal',biweekly:'Quincenal',quincenal:'Quincenal',monthly:'Mensual',mensual:'Mensual',bimonthly:'Bimestral',bimestral:'Bimestral',quarterly:'Trimestral',trimestral:'Trimestral',semiannual:'Semestral',semestral:'Semestral',yearly:'Anual',annual:'Anual',anual:'Anual'}[String(v).toLowerCase()]??v)
function recurringStatus(r:Row){if(!r.active)return 'Inactivo';if(!r.next_due_date)return 'Sin fecha';const due=new Date(`${r.next_due_date}T12:00:00`).getTime(),now=new Date(`${today()}T12:00:00`).getTime(),days=Math.round((due-now)/86400000);if(days<0)return 'Vencido';if(days<=7)return 'Por pagar';return 'Próximo'}
function dateLabel(v:string|null|undefined){return v?new Date(`${v}T12:00:00`).toLocaleDateString('es-MX'):'Sin fecha'}

export function FinanceAdminPage({businessId,userId}:{businessId:string;userId:string}){
 const [tab,setTab]=useState<Tab>('badDebts'),[rows,setRows]=useState<Row[]>([]),[customers,setCustomers]=useState<Row[]>([]),[accounts,setAccounts]=useState<Row[]>([]),[expenses,setExpenses]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[open,setOpen]=useState(false),[paying,setPaying]=useState<Row|null>(null),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null)
 async function load(){if(!supabase)return;const tables:Record<Tab,string>={badDebts:'bad_debts',recurring:'recurring_expenses',allocations:'expense_allocations',periods:'financial_periods',audit:'audit_log'};const [r,c,a,e,o]=await Promise.all([supabase.from(tables[tab]).select('*').eq('business_id',businessId).order(tab==='periods'?'year':'created_at',{ascending:false}).limit(150),supabase.from('customers').select('id,name').eq('business_id',businessId).eq('active',true).is('deleted_at',null),supabase.from('financial_account_balances').select('account_id,name').eq('business_id',businessId),supabase.from('expenses').select('id,category,amount,expense_date').eq('business_id',businessId).neq('status','cancelled').order('expense_date',{ascending:false}).limit(100),supabase.from('orders').select('id,folio,total').eq('business_id',businessId).is('deleted_at',null).order('created_at',{ascending:false}).limit(100)]);if(r.error)setError(r.error.message);else if(o.error)setError(o.error.message);else setError(null);setRows(r.data??[]);setCustomers(c.data??[]);setAccounts(a.data??[]);setExpenses(e.data??[]);setOrders(o.data??[])}
 useEffect(()=>{void load()},[businessId,tab])
 async function action(r:Row){if(!supabase)return;if(tab==='badDebts'){const amount=window.prompt('Monto recuperado');if(!amount)return;const account=window.prompt('ID de cuenta financiera para recibir la recuperación (opcional)')||null;const {error}=await supabase.from('bad_debt_recoveries').insert({business_id:businessId,bad_debt_id:r.id,account_id:account,amount:n(amount),created_by:userId});if(error)setError(error.message)}else if(tab==='periods'){const status=r.status==='closed'?'reopened':'closed';const {error}=await supabase.from('financial_periods').update({status}).eq('id',r.id).eq('business_id',businessId);if(error)setError(error.message)}void load()}
 return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Administración financiera</span><h1>Control y cierre financiero</h1><p>Incobrables, recurrencias, asignaciones a pedidos, cierres mensuales y trazabilidad.</p></div>{tab!=='audit'&&<button className="primary-button primary-button--auto" onClick={()=>setOpen(true)}><Plus size={17}/>Nuevo</button>}</div><div className="module-tabs">{(Object.keys(labels) as Tab[]).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setMessage(null)}}>{labels[t]}</button>)}</div>{message&&<div className="notice notice--success">{message}</div>}{error&&<div className="notice notice--error">{error}</div>}<div className="data-card"><div className="data-list">{rows.length===0?<div className="empty-state"><strong>Sin registros</strong></div>:rows.map(r=><div className="data-row" key={r.id}><div className="data-row__main"><strong>{title(tab,r,customers,expenses,orders)}</strong><span>{detail(tab,r,accounts)}</span>{tab==='recurring'&&r.last_paid_at&&<span>Último pago: {money.format(n(r.last_paid_amount))} · {new Date(r.last_paid_at).toLocaleDateString('es-MX')}</span>}</div><div className="data-row__meta">{amount(tab,r)&&<strong>{amount(tab,r)}</strong>}<span className="badge">{tab==='recurring'?recurringStatus(r):(r.status??r.action??'Registrado')}</span>{tab==='recurring'&&r.active&&<button className="mini-action" onClick={()=>setPaying(r)}>Registrar pago</button>}{tab==='badDebts'&&r.status!=='recovered'&&<button className="mini-action" onClick={()=>void action(r)}>Registrar recuperación</button>}{tab==='periods'&&<button className="mini-action" onClick={()=>void action(r)}>{r.status==='closed'?'Reabrir':'Cerrar mes'}</button>}</div></div>)}</div></div>{open&&<Create tab={tab} businessId={businessId} userId={userId} customers={customers} accounts={accounts} expenses={expenses} orders={orders} close={()=>setOpen(false)} done={()=>{setOpen(false);void load()}}/>}{paying&&<PayRecurring row={paying} accounts={accounts} close={()=>setPaying(null)} done={(next,paid)=>{setPaying(null);setMessage(`Pago de ${money.format(paid)} registrado. Próximo vencimiento: ${next?dateLabel(next):'sin fecha'}.`);void load()}}/>}</>
}
function title(t:Tab,r:Row,c:Row[],e:Row[],o:Row[]){if(t==='badDebts')return c.find(x=>x.id===r.customer_id)?.name??'Cliente';if(t==='recurring')return r.description;if(t==='allocations')return `${e.find(x=>x.id===r.expense_id)?.category??'Gasto'} → ${o.find(x=>x.id===r.order_id)?.folio??'Pedido'}`;if(t==='periods')return `${String(r.month).padStart(2,'0')}/${r.year}`;return `${r.action} · ${r.entity_type}`}
function detail(t:Tab,r:Row,a:Row[]){if(t==='badDebts')return `${r.reason??'Sin motivo'} · ${r.declared_at}`;if(t==='recurring'){const account=a.find(x=>x.account_id===r.account_id)?.name;return `${r.category} · ${frequencyLabel(r.frequency)} · vence ${dateLabel(r.next_due_date)}${account?` · ${account}`:''}`}if(t==='allocations')return 'Asignación de gasto al costo del pedido';if(t==='periods')return r.closed_at?`Cerrado ${new Date(r.closed_at).toLocaleString('es-MX')}`:'Periodo abierto';return `${new Date(r.created_at).toLocaleString('es-MX')} · usuario ${r.user_id??'sistema'}`}
function amount(t:Tab,r:Row){if(t==='badDebts')return money.format(n(r.amount));if(t==='recurring')return r.expected_amount==null?'':money.format(n(r.expected_amount));if(t==='allocations')return money.format(n(r.amount));return ''}

function PayRecurring({row,accounts,close,done}:{row:Row;accounts:Row[];close:()=>void;done:(next:string|null,amount:number)=>void}){
 const [amount,setAmount]=useState(String(row.expected_amount??'')),[account,setAccount]=useState(String(row.account_id??'')),[date,setDate]=useState(today()),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null)
 async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;if(!account){setError('Selecciona una cuenta financiera para indicar de dónde salió el dinero.');return}setSaving(true);setError(null);const {data,error:rpcError}=await supabase.rpc('pay_recurring_expense',{p_recurring_expense_id:row.id,p_amount:n(amount),p_account_id:account,p_paid_date:date});setSaving(false);if(rpcError){setError(rpcError.message);return}const result=Array.isArray(data)?data[0]:data;done(result?.next_due_date??null,n(result?.paid_amount??amount))}
 return <div className="modal-backdrop"><section className="modal-card"><div className="modal-card__header"><div><span className="eyebrow">Gasto recurrente</span><h2>Registrar pago</h2></div><button type="button" className="icon-button" onClick={close}>×</button></div><form className="entity-form" onSubmit={submit}><div className="notice"><strong>{row.description}</strong><br/>Vencimiento actual: {dateLabel(row.next_due_date)}</div><label>Monto pagado<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Cuenta financiera<select required value={account} onChange={e=>setAccount(e.target.value)}><option value="">Selecciona de dónde salió el dinero</option>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.name}</option>)}</select></label>{accounts.length===0&&<div className="notice notice--error">Todavía no tienes cuentas financieras activas. Crea primero una cuenta en Finanzas para poder registrar el pago y afectar el saldo correcto.</div>}<label>Fecha de pago<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={saving||accounts.length===0}>{saving?'Registrando…':'Registrar pago'}</button></div></form></section></div>
}

function Create({tab,businessId,userId,customers,accounts,expenses,orders,close,done}:{tab:Tab;businessId:string;userId:string;customers:Row[];accounts:Row[];expenses:Row[];orders:Row[];close:()=>void;done:()=>void}){
 const [f,setF]=useState<Record<string,string>>({amountType:'fixed',frequency:'monthly',month:String(new Date().getMonth()+1),year:String(new Date().getFullYear())}),[error,setError]=useState<string|null>(null);const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}))
 async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;let table='',p:Row={business_id:businessId};if(tab==='badDebts'){table='bad_debts';p={...p,customer_id:f.customer,amount:n(f.amount),reason:f.reason||null,authorized_by:userId,status:'written_off'}}if(tab==='recurring'){table='recurring_expenses';p={...p,category:f.category,description:f.description,amount_type:f.amountType,expected_amount:f.amount?n(f.amount):null,frequency:f.frequency,account_id:f.account||null,next_due_date:f.date||null,active:true,notes:f.notes||null}}if(tab==='allocations'){table='expense_allocations';p={...p,expense_id:f.expense,order_id:f.order,amount:n(f.amount)}}if(tab==='periods'){table='financial_periods';p={...p,year:Number(f.year),month:Number(f.month),status:'open',notes:f.notes||null}}const {error}=await supabase.from(table).insert(p);if(error)setError(error.message);else done()}
 return <div className="modal-backdrop"><section className="modal-card"><div className="modal-card__header"><h2>Nuevo · {labels[tab]}</h2><button type="button" className="icon-button" onClick={close}>×</button></div><form className="entity-form" onSubmit={submit}>{tab==='badDebts'&&<><Select label="Cliente" rows={customers} valueKey="id" textKey="name" onChange={v=>set('customer',v)}/><Money set={set}/><label>Motivo<textarea rows={3} onChange={e=>set('reason',e.target.value)}/></label></>}{tab==='recurring'&&<><label>Categoría<input required onChange={e=>set('category',e.target.value)}/></label><label>Descripción<input required onChange={e=>set('description',e.target.value)}/></label><label>Tipo de monto<select value={f.amountType} onChange={e=>set('amountType',e.target.value)}><option value="fixed">Fijo</option><option value="variable">Variable</option></select></label><Money set={set}/><label>Frecuencia<select required value={f.frequency} onChange={e=>set('frequency',e.target.value)}><option value="weekly">Semanal</option><option value="biweekly">Quincenal</option><option value="monthly">Mensual</option><option value="bimonthly">Bimestral</option><option value="quarterly">Trimestral</option><option value="semiannual">Semestral</option><option value="yearly">Anual</option></select></label><Select label="Cuenta predeterminada" rows={accounts} valueKey="account_id" textKey="name" required={false} onChange={v=>set('account',v)}/><label>Próximo vencimiento<input type="date" onChange={e=>set('date',e.target.value)}/></label><label>Notas<textarea rows={3} onChange={e=>set('notes',e.target.value)}/></label></>}{tab==='allocations'&&<><Select label="Gasto" rows={expenses.map(x=>({...x,label:`${x.category} · ${money.format(n(x.amount))}`}))} valueKey="id" textKey="label" onChange={v=>set('expense',v)}/><Select label="Pedido" rows={orders.map(x=>({...x,label:`${x.folio} · ${money.format(n(x.total))}`}))} valueKey="id" textKey="label" onChange={v=>set('order',v)}/><Money set={set}/></>}{tab==='periods'&&<><label>Año<input required type="number" min="2000" max="2200" value={f.year} onChange={e=>set('year',e.target.value)}/></label><label>Mes<input required type="number" min="1" max="12" value={f.month} onChange={e=>set('month',e.target.value)}/></label><label>Notas<textarea rows={3} onChange={e=>set('notes',e.target.value)}/></label></>}{error&&<div className="notice notice--error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button">Guardar</button></div></form></section></div>
}
function Select({label,rows,valueKey,textKey,onChange,required=true}:{label:string;rows:Row[];valueKey:string;textKey:string;onChange:(v:string)=>void;required?:boolean}){return <label>{label}<select required={required} onChange={e=>onChange(e.target.value)}><option value="">Selecciona</option>{rows.map(r=><option key={r[valueKey]} value={r[valueKey]}>{r[textKey]}</option>)}</select></label>}
function Money({set}:{set:(k:string,v:string)=>void}){return <label>Monto<input required type="number" min="0.01" step="0.01" onChange={e=>set('amount',e.target.value)}/></label>}
