import { FormEvent,useEffect,useMemo,useState } from 'react'
import { Bus,CarFront,Fuel } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Order={id:string;folio:string;status:string;customer:{name:string}|null}
type Account={id:string;name:string}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const n=(value:string)=>Number(value||0)

export function OrderTransportExpensePanel({businessId,userId}:{businessId:string;userId:string}){
 const[orders,setOrders]=useState<Order[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[orderId,setOrderId]=useState(''),[accountId,setAccountId]=useState(''),[kind,setKind]=useState<'bus'|'fuel'>('bus'),[outbound,setOutbound]=useState(''),[returnFare,setReturnFare]=useState(''),[fuel,setFuel]=useState(''),[notes,setNotes]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null)
 useEffect(()=>{if(!supabase)return;void(async()=>{const[o,a]=await Promise.all([supabase.from('orders').select('id,folio,status,customer:customers(name)').eq('business_id',businessId).is('deleted_at',null).neq('status','cancelled').order('created_at',{ascending:false}),supabase.from('financial_accounts').select('id,name').eq('business_id',businessId).eq('active',true).order('name')]);if(o.error||a.error){setError(o.error?.message??a.error?.message??null);return}const os=(o.data??[]) as unknown as Order[],as=(a.data??[]) as Account[];setOrders(os);setAccounts(as);setOrderId(os[0]?.id??'');setAccountId(as[0]?.id??'')})()},[businessId])
 const selected=useMemo(()=>orders.find(o=>o.id===orderId),[orders,orderId]);const amount=kind==='bus'?n(outbound)+n(returnFare):n(fuel)
 async function submit(e:FormEvent){e.preventDefault();if(!supabase||!orderId||!accountId)return;setError(null);setMessage(null);if(amount<=0){setError('Ingresa un gasto mayor a $0.');return}if(kind==='bus'&&(n(outbound)<=0||n(returnFare)<=0)){setError('Para camión registra tanto ida como regreso.');return}setSaving(true);const detail=kind==='bus'?`Camión: ida ${money.format(n(outbound))} + regreso ${money.format(n(returnFare))}`:`Gasolina: ${money.format(amount)}`;const{data:expense,error:ee}=await supabase.from('expenses').insert({business_id:businessId,category:kind==='bus'?'Transporte - Camión':'Gasolina',account_id:accountId,amount,business_amount:amount,personal_amount:0,status:'paid',notes:[selected?.folio,detail,notes.trim()].filter(Boolean).join(' · '),created_by:userId}).select('id').single();if(ee||!expense){setError(ee?.message??'No se pudo registrar el gasto.');setSaving(false);return}const{error:ae}=await supabase.from('expense_allocations').insert({business_id:businessId,expense_id:expense.id,order_id:orderId,amount});if(ae){await supabase.from('expenses').delete().eq('id',expense.id);setError(ae.message);setSaving(false);return}setOutbound('');setReturnFare('');setFuel('');setNotes('');setMessage(`${detail} registrado y vinculado al pedido ${selected?.folio??''}.`);setSaving(false)}
 return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Logística y costeo</span><h2>Transporte por pedido</h2><p>Registra camión ida/regreso o gasolina como gasto real y asígnalo directamente al pedido.</p></div></div>{error&&<div className="notice notice--error">{error}</div>}{message&&<div className="notice">{message}</div>}<form className="panel entity-form" onSubmit={submit}><div className="form-grid"><label>Pedido<select required value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Selecciona…</option>{orders.map(o=><option key={o.id} value={o.id}>{o.folio} · {o.customer?.name??'Cliente'}</option>)}</select></label><label>Cuenta de pago<select required value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Selecciona…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><div className="module-tabs"><button type="button" className={kind==='bus'?'active':''} onClick={()=>setKind('bus')}><Bus size={16}/> Camión ida/regreso</button><button type="button" className={kind==='fuel'?'active':''} onClick={()=>setKind('fuel')}><Fuel size={16}/> Gasolina</button></div>{kind==='bus'?<div className="form-grid"><label>Pasaje de ida<input required min="0" step="0.01" type="number" value={outbound} onChange={e=>setOutbound(e.target.value)}/></label><label>Pasaje de regreso<input required min="0" step="0.01" type="number" value={returnFare} onChange={e=>setReturnFare(e.target.value)}/></label></div>:<label>Gasto de gasolina<input required min="0" step="0.01" type="number" value={fuel} onChange={e=>setFuel(e.target.value)}/></label>}<label>Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ej. recolección de material del proveedor"/></label><div className="detail-grid"><div className="detail-item"><span>Tipo</span><strong>{kind==='bus'?'Camión ida/regreso':'Gasolina'}</strong></div><div className="detail-item"><span>Total a registrar</span><strong>{money.format(amount)}</strong></div></div><button className="primary-button primary-button--auto" disabled={saving||orders.length===0||accounts.length===0}><CarFront size={17}/>{saving?'Registrando…':'Registrar gasto y vincular'}</button></form>{orders.length===0&&<div className="notice">No hay pedidos activos para asociar.</div>}{accounts.length===0&&<div className="notice">Primero configura una cuenta financiera activa.</div>}</>
}
