import { FormEvent, useEffect, useMemo, useState } from 'react'
import { BadgeDollarSign, Boxes, PackagePlus, Plus, Search, Settings2, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './finance-suppliers.css'

type Product={id:string;name:string;description:string|null;product_type:'manufactured'|'resale'|'mixed'|'service';category:string|null;base_price:number|string|null;active:boolean}
type Variant={id:string;product_id:string;sku:string|null;name:string;price:number|string|null;active:boolean}
type Attr={id:string;name:string;code:string}
type AttrValue={id:string;attribute_id:string;value:string}
type VariantValue={product_variant_id:string;attribute_id:string;value_id:string}
type Price={id:string;product_id:string|null;variant_id:string|null;price_type:'retail'|'wholesale'|'special';min_quantity:number|string;amount:number|string;valid_from:string;valid_to:string|null;active:boolean}
type Recipe={id:string;product_id:string|null;variant_id:string|null;name:string;version:number;yield_quantity:number|string;yield_unit:string;active:boolean;notes:string|null}
type RecipeItem={id:string;recipe_id:string;material_id:string;quantity:number|string;unit:string;waste_percent:number|string;notes:string|null;materials:{name:string}|null}
type Material={id:string;name:string;base_unit:string}
type Profit={product_id:string;revenue:number|string|null;actual_cost:number|string|null;actual_margin:number|string|null;actual_margin_pct:number|string|null}
type Modal='product'|'variant'|'price'|'recipe'|'recipeItem'|null
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const num=(v:unknown)=>Number.isFinite(Number(v??0))?Number(v??0):0

export function ProductsPage({businessId}:{businessId:string}){
 const [products,setProducts]=useState<Product[]>([]),[variants,setVariants]=useState<Variant[]>([]),[attrs,setAttrs]=useState<Attr[]>([]),[attrValues,setAttrValues]=useState<AttrValue[]>([]),[variantValues,setVariantValues]=useState<VariantValue[]>([]),[prices,setPrices]=useState<Price[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]),[recipeItems,setRecipeItems]=useState<RecipeItem[]>([]),[materials,setMaterials]=useState<Material[]>([]),[profits,setProfits]=useState<Profit[]>([])
 const [selected,setSelected]=useState<Product|null>(null),[editing,setEditing]=useState<Product|null>(null),[modal,setModal]=useState<Modal>(null),[recipeTarget,setRecipeTarget]=useState<Recipe|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 async function load(){if(!supabase)return;setLoading(true);setError(null);const [p,v,a,av,pvv,pr,r,ri,m,pf]=await Promise.all([
  supabase.from('products').select('id,name,description,product_type,category,base_price,active').eq('business_id',businessId).is('deleted_at',null).order('name'),
  supabase.from('product_variants').select('id,product_id,sku,name,price,active').eq('business_id',businessId).eq('active',true).order('name'),
  supabase.from('variant_attributes').select('id,name,code').eq('business_id',businessId).eq('active',true).order('name'),
  supabase.from('variant_attribute_values').select('id,attribute_id,value').eq('business_id',businessId).eq('active',true).order('sort_order').order('value'),
  supabase.from('product_variant_values').select('product_variant_id,attribute_id,value_id').eq('business_id',businessId),
  supabase.from('product_prices').select('id,product_id,variant_id,price_type,min_quantity,amount,valid_from,valid_to,active').eq('business_id',businessId).eq('active',true).order('valid_from',{ascending:false}),
  supabase.from('product_recipes').select('id,product_id,variant_id,name,version,yield_quantity,yield_unit,active,notes').eq('business_id',businessId).eq('active',true).order('created_at',{ascending:false}),
  supabase.from('product_recipe_items').select('id,recipe_id,material_id,quantity,unit,waste_percent,notes,materials(name)').order('created_at'),
  supabase.from('materials').select('id,name,base_unit').eq('business_id',businessId).eq('active',true).is('deleted_at',null).order('name'),
  supabase.from('product_profitability').select('product_id,revenue,actual_cost,actual_margin,actual_margin_pct').eq('business_id',businessId)]);
 const first=[p,v,a,av,pvv,pr,r,ri,m,pf].find(x=>x.error);if(first?.error)setError(first.error.message);setProducts((p.data??[]) as Product[]);setVariants((v.data??[]) as Variant[]);setAttrs((a.data??[]) as Attr[]);setAttrValues((av.data??[]) as AttrValue[]);setVariantValues((pvv.data??[]) as VariantValue[]);setPrices((pr.data??[]) as Price[]);setRecipes((r.data??[]) as Recipe[]);setRecipeItems((ri.data??[]) as unknown as RecipeItem[]);setMaterials((m.data??[]) as Material[]);setProfits((pf.data??[]) as Profit[]);setLoading(false)}
 useEffect(()=>{void load()},[businessId])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return products.filter(p=>!q||[p.name,p.category,p.product_type].some(v=>v?.toLowerCase().includes(q)))},[products,query])
 const selectedVariants=selected?variants.filter(v=>v.product_id===selected.id):[]
 const selectedPrices=selected?prices.filter(p=>p.product_id===selected.id||selectedVariants.some(v=>v.id===p.variant_id)):[]
 const selectedRecipes=selected?recipes.filter(r=>r.product_id===selected.id||selectedVariants.some(v=>v.id===r.variant_id)):[]
 const profit=selected?profits.find(p=>p.product_id===selected.id):null
 function attrText(variantId:string){return variantValues.filter(v=>v.product_variant_id===variantId).map(link=>{const a=attrs.find(x=>x.id===link.attribute_id);const val=attrValues.find(x=>x.id===link.value_id);return a&&val?`${a.name}: ${val.value}`:null}).filter(Boolean).join(' · ')}
 function openEdit(p:Product){setEditing(p);setModal('product')}
 return <>
 <div className="page-heading page-heading--actions"><div><span className="eyebrow">Catálogo</span><h1>Productos</h1><p>Productos, servicios, variantes, precios, recetas y rentabilidad.</p></div><button className="primary-button primary-button--auto" onClick={()=>{setEditing(null);setModal('product')}}><Plus size={17}/>Nuevo producto</button></div>
 <div className="toolbar"><div className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto…"/></div><span className="toolbar__count">{visible.length} productos/servicios</span></div>{error&&<div className="notice notice--error">{error}</div>}
 <div className="data-card"><div className="data-list">{loading?<div className="empty-state">Cargando…</div>:visible.length===0?<div className="empty-state"><Boxes size={28}/><strong>Sin productos</strong><span>Crea el primero para usar pedidos, precios y cotizaciones.</span></div>:visible.map(p=><button className="data-row" key={p.id} onClick={()=>setSelected(p)}><div className="data-row__avatar"><Boxes size={18}/></div><div className="data-row__main"><strong>{p.name}</strong><span>{typeLabel(p.product_type)}{p.category?` · ${p.category}`:''}</span></div><div className="data-row__meta"><strong>{p.base_price==null?'Sin precio base':money.format(num(p.base_price))}</strong><span>{variants.filter(v=>v.product_id===p.id).length} variante(s)</span></div></button>)}</div></div>
 {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="detail-drawer detail-drawer--wide" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">Producto / servicio</span><h2>{selected.name}</h2><p>{typeLabel(selected.product_type)}{selected.category?` · ${selected.category}`:''}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="supplier-actions"><button className="secondary-button" onClick={()=>openEdit(selected)}>Editar</button><button className="secondary-button" onClick={()=>setModal('variant')}><Plus size={15}/>Variante</button><button className="secondary-button" onClick={()=>setModal('price')}><BadgeDollarSign size={15}/>Precio</button><button className="secondary-button" onClick={()=>setModal('recipe')}><PackagePlus size={15}/>Receta</button></div>
 <section className="drawer-section"><h3>Rentabilidad real</h3><div className="supplier-metrics"><div><span>Ventas</span><strong>{money.format(num(profit?.revenue))}</strong></div><div><span>Costo real</span><strong>{money.format(num(profit?.actual_cost))}</strong></div><div><span>Margen</span><strong>{money.format(num(profit?.actual_margin))}</strong></div><div><span>Margen %</span><strong>{num(profit?.actual_margin_pct).toFixed(1)}%</strong></div></div></section>
 <section className="drawer-section"><h3>Variantes flexibles</h3>{selectedVariants.length===0?<Empty text="Sin variantes."/>:<div className="line-items">{selectedVariants.map(v=><div className="line-item" key={v.id}><div><strong>{v.name}</strong><span>{attrText(v.id)||'Sin atributos asignados'}{v.sku?` · SKU ${v.sku}`:''}</span></div><strong>{v.price==null?'—':money.format(num(v.price))}</strong></div>)}</div>}</section>
 <section className="drawer-section"><h3>Precios vigentes</h3>{selectedPrices.length===0?<Empty text="Sin precios configurados."/>:<div className="line-items">{selectedPrices.map(p=><div className="line-item" key={p.id}><div><strong>{priceTypeLabel(p.price_type)} · desde {num(p.min_quantity)}</strong><span>{p.variant_id?variants.find(v=>v.id===p.variant_id)?.name||'Variante':'Producto general'}</span></div><strong>{money.format(num(p.amount))}</strong></div>)}</div>}</section>
 <section className="drawer-section"><h3>Recetas / BOM</h3>{selectedRecipes.length===0?<Empty text={materials.length===0?'Crea materiales para construir recetas.':'Sin recetas.'}/>:<div className="line-items">{selectedRecipes.map(r=><div className="line-item line-item--stack" key={r.id}><div className="line-item__top"><div><strong>{r.name} · v{r.version}</strong><span>Rinde {num(r.yield_quantity)} {r.yield_unit}{r.variant_id?` · ${variants.find(v=>v.id===r.variant_id)?.name||'Variante'}`:''}</span></div><button className="secondary-button secondary-button--small" onClick={()=>{setRecipeTarget(r);setModal('recipeItem')}}><Plus size={14}/>Material</button></div><div className="recipe-lines">{recipeItems.filter(i=>i.recipe_id===r.id).map(i=><span key={i.id}>{i.materials?.name||'Material'}: {num(i.quantity)} {i.unit}{num(i.waste_percent)>0?` + ${num(i.waste_percent)}% merma`:''}</span>)}</div></div>)}</div>}</section>
 </aside></div>}
 {modal==='product'&&<ProductModal businessId={businessId} editing={editing} close={()=>setModal(null)} done={async()=>{setModal(null);setEditing(null);await load();setSelected(null)}}/>}
 {modal==='variant'&&selected&&<VariantModal businessId={businessId} product={selected} attrs={attrs} values={attrValues} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 {modal==='price'&&selected&&<PriceModal businessId={businessId} product={selected} variants={selectedVariants} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 {modal==='recipe'&&selected&&<RecipeModal businessId={businessId} product={selected} variants={selectedVariants} materials={materials} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 {modal==='recipeItem'&&recipeTarget&&<RecipeItemModal recipe={recipeTarget} materials={materials} close={()=>{setModal(null);setRecipeTarget(null)}} done={async()=>{setModal(null);setRecipeTarget(null);await load()}}/>}
 </>
}
function typeLabel(t:Product['product_type']){return t==='manufactured'?'Fabricado':t==='resale'?'Reventa':t==='mixed'?'Mixto':'Servicio'}
function priceTypeLabel(t:Price['price_type']){return t==='retail'?'Menudeo':t==='wholesale'?'Mayoreo':'Especial'}
function Empty({text}:{text:string}){return <div className="empty-state empty-state--compact">{text}</div>}
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="form-modal"><div className="drawer-header"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={19}/></button></div>{children}</div></div>}
function Actions({close}:{close:()=>void}){return <div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button primary-button--auto">Guardar</button></div>}
function ProductModal({businessId,editing,close,done}:{businessId:string;editing:Product|null;close:()=>void;done:()=>void}){const [name,setName]=useState(editing?.name??''),[type,setType]=useState<Product['product_type']>(editing?.product_type??'manufactured'),[category,setCategory]=useState(editing?.category??''),[basePrice,setBasePrice]=useState(editing?.base_price==null?'':String(editing.base_price)),[description,setDescription]=useState(editing?.description??''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const payload={business_id:businessId,name:name.trim(),product_type:type,category:category.trim()||null,base_price:basePrice===''?null:num(basePrice),description:description.trim()||null,active:true,updated_at:new Date().toISOString()};const result=editing?await supabase.from('products').update(payload).eq('id',editing.id).eq('business_id',businessId):await supabase.from('products').insert(payload);if(result.error)setError(result.error.message);else done()}return <Shell title={editing?'Editar producto':'Nuevo producto / servicio'} close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value as Product['product_type'])}><option value="manufactured">Fabricado</option><option value="resale">Reventa</option><option value="mixed">Mixto</option><option value="service">Servicio</option></select></label><label>Categoría<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Playeras, Tazas, Lonas…"/></label><label>Precio base<input type="number" min="0" step="0.01" value={basePrice} onChange={e=>setBasePrice(e.target.value)}/></label><label className="form-span-2">Descripción<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function VariantModal({businessId,product,attrs,values,close,done}:{businessId:string;product:Product;attrs:Attr[];values:AttrValue[];close:()=>void;done:()=>void}){const [name,setName]=useState(''),[sku,setSku]=useState(''),[price,setPrice]=useState(''),[entries,setEntries]=useState<Record<string,string>>({}),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const attributes:Object=Object.fromEntries(attrs.map(a=>[a.code,(entries[a.id]||'').trim()]).filter(([,v])=>v));const {data:variant,error}=await supabase.from('product_variants').insert({business_id:businessId,product_id:product.id,name:name.trim(),sku:sku.trim()||null,price:price===''?null:num(price),attributes}).select('id').single();if(error){setError(error.message);return}for(const attr of attrs){const value=(entries[attr.id]||'').trim();if(!value)continue;let valueId=values.find(v=>v.attribute_id===attr.id&&v.value.toLowerCase()===value.toLowerCase())?.id;if(!valueId){const created=await supabase.from('variant_attribute_values').insert({business_id:businessId,attribute_id:attr.id,value}).select('id').single();if(created.error){setError(created.error.message);return}valueId=created.data.id}const linked=await supabase.from('product_variant_values').insert({business_id:businessId,product_variant_id:variant.id,attribute_id:attr.id,value_id:valueId});if(linked.error){setError(linked.error.message);return}}done()}return <Shell title={`Nueva variante · ${product.name}`} close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Nombre de variante<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Negra M Yazbek"/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)}/></label><label>Precio opcional<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label></div><div className="form-grid">{attrs.map(a=><label key={a.id}>{a.name}<input list={`attr-${a.id}`} value={entries[a.id]||''} onChange={e=>setEntries({...entries,[a.id]:e.target.value})}/><datalist id={`attr-${a.id}`}>{values.filter(v=>v.attribute_id===a.id).map(v=><option key={v.id} value={v.value}/>)}</datalist></label>)}</div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function PriceModal({businessId,product,variants,close,done}:{businessId:string;product:Product;variants:Variant[];close:()=>void;done:()=>void}){const [variant,setVariant]=useState(''),[type,setType]=useState<Price['price_type']>('retail'),[qty,setQty]=useState('1'),[amount,setAmount]=useState(''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const payload={business_id:businessId,product_id:variant?null:product.id,variant_id:variant||null,price_type:type,min_quantity:num(qty),amount:num(amount),currency:'MXN'};const {error}=await supabase.from('product_prices').insert(payload);if(error)setError(error.message);else done()}return <Shell title={`Nuevo precio · ${product.name}`} close={close}><form className="entity-form" onSubmit={submit}><label>Aplicar a<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="">Producto general</option>{variants.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="form-grid"><label>Tipo<select value={type} onChange={e=>setType(e.target.value as Price['price_type'])}><option value="retail">Menudeo</option><option value="wholesale">Mayoreo</option><option value="special">Especial</option></select></label><label>Cantidad mínima<input required type="number" min="0.01" step="0.01" value={qty} onChange={e=>setQty(e.target.value)}/></label><label>Precio<input required type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function RecipeModal({businessId,product,variants,materials,close,done}:{businessId:string;product:Product;variants:Variant[];materials:Material[];close:()=>void;done:()=>void}){const [variant,setVariant]=useState(''),[name,setName]=useState('Receta principal'),[yieldQty,setYieldQty]=useState('1'),[yieldUnit,setYieldUnit]=useState('pieza'),[material,setMaterial]=useState(''),[qty,setQty]=useState(''),[unit,setUnit]=useState(''),[waste,setWaste]=useState('0'),[notes,setNotes]=useState(''),[error,setError]=useState<string|null>(null);useEffect(()=>{const m=materials.find(x=>x.id===material);if(m)setUnit(m.base_unit)},[material,materials]);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {data:recipe,error}=await supabase.from('product_recipes').insert({business_id:businessId,product_id:variant?null:product.id,variant_id:variant||null,name:name.trim(),yield_quantity:num(yieldQty),yield_unit:yieldUnit.trim()||'pieza',notes:notes.trim()||null}).select('id').single();if(error){setError(error.message);return}if(material&&qty){const item=await supabase.from('product_recipe_items').insert({recipe_id:recipe.id,material_id:material,quantity:num(qty),unit:unit||materials.find(x=>x.id===material)?.base_unit||'piece',waste_percent:num(waste)});if(item.error){setError(item.error.message);return}}done()}return <Shell title={`Nueva receta · ${product.name}`} close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Aplicar a<select value={variant} onChange={e=>setVariant(e.target.value)}><option value="">Producto general</option>{variants.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Rendimiento<input type="number" min="0.01" step="0.01" value={yieldQty} onChange={e=>setYieldQty(e.target.value)}/></label><label>Unidad de rendimiento<input value={yieldUnit} onChange={e=>setYieldUnit(e.target.value)}/></label></div><h3>Primer material (opcional)</h3><div className="form-grid"><label>Material<select value={material} onChange={e=>setMaterial(e.target.value)}><option value="">Sin material inicial</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Cantidad<input type="number" min="0" step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></label><label>Unidad<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Merma %<input type="number" min="0" step="0.01" value={waste} onChange={e=>setWaste(e.target.value)}/></label></div><label>Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
function RecipeItemModal({recipe,materials,close,done}:{recipe:Recipe;materials:Material[];close:()=>void;done:()=>void}){const [material,setMaterial]=useState(''),[qty,setQty]=useState(''),[unit,setUnit]=useState(''),[waste,setWaste]=useState('0'),[notes,setNotes]=useState(''),[error,setError]=useState<string|null>(null);useEffect(()=>{const m=materials.find(x=>x.id===material);if(m)setUnit(m.base_unit)},[material,materials]);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('product_recipe_items').insert({recipe_id:recipe.id,material_id:material,quantity:num(qty),unit:unit||materials.find(x=>x.id===material)?.base_unit||'piece',waste_percent:num(waste),notes:notes.trim()||null});if(error)setError(error.message);else done()}return <Shell title={`Agregar material · ${recipe.name}`} close={close}><form className="entity-form" onSubmit={submit}><label>Material<select required value={material} onChange={e=>setMaterial(e.target.value)}><option value="">Selecciona</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="form-grid"><label>Cantidad<input required type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></label><label>Unidad<input required value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Merma %<input type="number" min="0" step="0.01" value={waste} onChange={e=>setWaste(e.target.value)}/></label></div><label>Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Shell>}
