import { FormEvent, useEffect, useMemo, useState } from 'react'
import { PackagePlus, Plus, Search, Truck, X } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Supplier={id:string;name:string}
type Variant={id:string;name:string;materials:{name:string}|null}
type Location={id:string;name:string}
type Purchase={id:string;supplier_id:string;purchase_number:string|null;status:string;ordered_at:string|null;expected_at:string|null;currency:string;subtotal:number|string;tax:number|string;total:number|string;notes:string|null;created_at:string;suppliers:{name:string}|null}
type Item={id:string;purchase_id:string;material_variant_id:string;description:string|null;quantity_ordered:number|string;quantity_received:number|string;unit_cost:number|string;status:string;material_variants:{name:string;materials:{name:string}|null}|null}
type Transit={purchase_id:string;purchase_item_id:string;quantity_in_transit:number|string;material_variant_id:string;expected_at:string|null}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});const n=(v:number|string|null|undefined)=>Number(v??0)||0
const purchaseStatuses=['draft','submitted','approved','partially_received','received','cancelled'] as const

export function PurchasesPage({businessId,userId}:{businessId:string;userId:string}){
  const [purchases,setPurchases]=useState<Purchase[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [variants,setVariants]=useState<Variant[]>([]);const [locations,setLocations]=useState<Location[]>([]);const [items,setItems]=useState<Item[]>([]);const [transit,setTransit]=useState<Transit[]>([]);const [selected,setSelected]=useState<Purchase|null>(null);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [createOpen,setCreateOpen]=useState(false);const [itemOpen,setItemOpen]=useState(false);const [receiptItem,setReceiptItem]=useState<Item|null>(null)
  async function load(){if(!supabase)return;setLoading(true);setError(null);const [p,s,v,l,i,t]=await Promise.all([
    supabase.from('purchases').select('id,supplier_id,purchase_number,status,ordered_at,expected_at,currency,subtotal,tax,total,notes,created_at,suppliers(name)').eq('business_id',businessId).is('deleted_at',null).order('created_at',{ascending:false}),
    supabase.from('suppliers').select('id,name').eq('business_id',businessId).eq('active',true).is('deleted_at',null).order('name'),
    supabase.from('material_variants').select('id,name,materials(name)').eq('business_id',businessId).eq('active',true).order('name'),
    supabase.from('locations').select('id,name').eq('business_id',businessId).eq('active',true).order('name'),
    supabase.from('purchase_items').select('id,purchase_id,material_variant_id,description,quantity_ordered,quantity_received,unit_cost,status,material_variants(name,materials(name))').eq('business_id',businessId).order('created_at'),
    supabase.from('purchase_in_transit').select('purchase_id,purchase_item_id,quantity_in_transit,material_variant_id,expected_at').eq('business_id',businessId)
  ]);const first=[p.error,s.error,v.error,l.error,i.error,t.error].find(Boolean);if(first)setError(first.message);setPurchases((p.data??[]) as unknown as Purchase[]);setSuppliers((s.data??[]) as Supplier[]);setVariants((v.data??[]) as unknown as Variant[]);setLocations((l.data??[]) as Location[]);setItems((i.data??[]) as unknown as Item[]);setTransit((t.data??[]) as Transit[]);setLoading(false);if(selected){const fresh=(p.data??[]).find(x=>x.id===selected.id);setSelected((fresh??null) as unknown as Purchase|null)}}
  useEffect(()=>{void load()},[businessId])
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return purchases.filter(p=>!q||[p.purchase_number,p.suppliers?.name,p.status].some(v=>v?.toLowerCase().includes(q)))},[purchases,search])
  const selectedItems=items.filter(i=>i.purchase_id===selected?.id);const selectedTransit=transit.filter(i=>i.purchase_id===selected?.id).reduce((a,b)=>a+n(b.quantity_in_transit),0)
  async function updateStatus(status:string){if(!supabase||!selected)return;const payload:Record<string,unknown>={status};if(status==='submitted'&&!selected.ordered_at)payload.ordered_at=new Date().toISOString();if(status==='approved'){payload.approved_by=userId;payload.approved_at=new Date().toISOString()}const {error:e}=await supabase.from('purchases').update(payload).eq('id',selected.id).eq('business_id',businessId);if(e){setError(e.message);return}await load()}
  return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Abastecimiento</span><h1>Compras</h1><p>Órdenes, partidas, material en tránsito y recepciones parciales conectadas al inventario.</p></div><button className="primary-button primary-button--inline" onClick={()=>setCreateOpen(true)}><Plus size={18}/> Nueva compra</button></div>{error&&<div className="notice notice--error">{error}</div>}<div className="toolbar"><div className="search-box"><Search size={18}/><input placeholder="Buscar folio, proveedor o estado…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="toolbar__count">{filtered.length} compras</span></div><div className="data-card"><div className="table-scroll"><table className="data-table"><thead><tr><th>Compra</th><th>Proveedor</th><th>Estado</th><th>Total</th><th>Esperada</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} onClick={()=>setSelected(p)}><td><strong>{p.purchase_number??'Sin folio'}</strong><small>{new Date(p.created_at).toLocaleDateString('es-MX')}</small></td><td>{p.suppliers?.name??'—'}</td><td><span className="tag">{p.status}</span></td><td><strong>{money.format(n(p.total))}</strong></td><td>{p.expected_at?new Date(p.expected_at).toLocaleDateString('es-MX'):'—'}</td></tr>)}</tbody></table></div>{!loading&&filtered.length===0&&<div className="empty-state"><Truck size={30}/><strong>No hay compras</strong><span>Crea la primera orden para empezar a controlar material en tránsito.</span></div>}</div>
  {selected&&<div className="drawer-backdrop"><aside className="drawer drawer--wide"><div className="drawer__header"><div><span className="eyebrow">Compra</span><h2>{selected.purchase_number??'Sin folio'}</h2><p>{selected.suppliers?.name}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="detail-grid"><div className="detail-item"><span>Estado</span><strong>{selected.status}</strong></div><div className="detail-item"><span>Total</span><strong>{money.format(n(selected.total))}</strong></div><div className="detail-item"><span>En tránsito</span><strong>{selectedTransit.toLocaleString('es-MX')}</strong></div><div className="detail-item"><span>Fecha esperada</span><strong>{selected.expected_at?new Date(selected.expected_at).toLocaleDateString('es-MX'):'—'}</strong></div></div><div className="drawer-section"><span className="eyebrow">Flujo</span><div className="status-actions">{purchaseStatuses.map(s=><button key={s} disabled={s===selected.status} className={s===selected.status?'status-button status-button--active':'status-button'} onClick={()=>void updateStatus(s)}>{s}</button>)}</div></div><div className="drawer-section"><div className="drawer-section__heading"><div><span className="eyebrow">Partidas</span><h3>Material solicitado</h3></div>{!['received','cancelled'].includes(selected.status)&&<button className="secondary-button secondary-button--small" onClick={()=>setItemOpen(true)}><Plus size={15}/> Agregar</button>}</div><div className="line-items">{selectedItems.map(item=>{const pending=Math.max(n(item.quantity_ordered)-n(item.quantity_received),0);return <div className="line-item" key={item.id}><div><strong>{item.material_variants?.materials?.name??'Material'} · {item.material_variants?.name}</strong><span>{n(item.quantity_received)} / {n(item.quantity_ordered)} recibidas · {item.status}</span></div><div><strong>{money.format(n(item.unit_cost))}</strong>{pending>0&&!['draft','cancelled'].includes(selected.status)&&<button className="secondary-button secondary-button--small" onClick={()=>setReceiptItem(item)}>Recibir {pending}</button>}</div></div>})}{selectedItems.length===0&&<div className="empty-state empty-state--compact">Sin partidas.</div>}</div><div className="totals-card"><div><span>Subtotal</span><strong>{money.format(n(selected.subtotal))}</strong></div><div><span>Impuesto</span><strong>{money.format(n(selected.tax))}</strong></div><div className="totals-card__total"><span>Total</span><strong>{money.format(n(selected.total))}</strong></div></div></div></aside></div>}
  {createOpen&&<CreatePurchaseDrawer businessId={businessId} userId={userId} suppliers={suppliers} onClose={()=>setCreateOpen(false)} onSaved={async()=>{setCreateOpen(false);await load()}}/>}
  {itemOpen&&selected&&<AddItemDrawer businessId={businessId} purchaseId={selected.id} variants={variants} onClose={()=>setItemOpen(false)} onSaved={async()=>{setItemOpen(false);await load()}}/>}
  {receiptItem&&selected&&<ReceiptDrawer businessId={businessId} userId={userId} purchaseId={selected.id} item={receiptItem} locations={locations} onClose={()=>setReceiptItem(null)} onSaved={async()=>{setReceiptItem(null);await load()}}/>}
  </>
}

function CreatePurchaseDrawer({businessId,userId,suppliers,onClose,onSaved}:{businessId:string;userId:string;suppliers:Supplier[];onClose:()=>void;onSaved:()=>Promise<void>}){const [supplier,setSupplier]=useState('');const [number,setNumber]=useState('');const [expected,setExpected]=useState('');const [notes,setNotes]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);const {error:err}=await supabase.from('purchases').insert({business_id:businessId,supplier_id:supplier,purchase_number:number||null,expected_at:expected?new Date(expected).toISOString():null,notes:notes||null,created_by:userId});if(err){setError(err.message);setSaving(false);return}await onSaved()}return <Drawer title="Nueva compra" onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="form-grid__wide">Proveedor<select required value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">Selecciona…</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Folio<input value={number} onChange={e=>setNumber(e.target.value)} placeholder="OC-001"/></label><label>Fecha esperada<input type="datetime-local" value={expected} onChange={e=>setExpected(e.target.value)}/></label><label className="form-grid__wide">Notas<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="notice notice--error form-grid__wide">{error}</div>}<Actions saving={saving} onClose={onClose}/></form></Drawer>}
function AddItemDrawer({businessId,purchaseId,variants,onClose,onSaved}:{businessId:string;purchaseId:string;variants:Variant[];onClose:()=>void;onSaved:()=>Promise<void>}){const [variant,setVariant]=useState('');const [quantity,setQuantity]=useState('');const [cost,setCost]=useState('');const [description,setDescription]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);const {error:err}=await supabase.from('purchase_items').insert({business_id:businessId,purchase_id:purchaseId,material_variant_id:variant,quantity_ordered:Number(quantity),unit_cost:Number(cost),description:description||null});if(err){setError(err.message);setSaving(false);return}await onSaved()}return <Drawer title="Agregar material" onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="form-grid__wide">Material<select required value={variant} onChange={e=>setVariant(e.target.value)}><option value="">Selecciona…</option>{variants.map(v=><option value={v.id} key={v.id}>{v.materials?.name} · {v.name}</option>)}</select></label><label>Cantidad<input required min="0.0001" step="0.0001" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Costo unitario<input required min="0" step="0.01" type="number" value={cost} onChange={e=>setCost(e.target.value)}/></label><label className="form-grid__wide">Descripción<input value={description} onChange={e=>setDescription(e.target.value)}/></label>{error&&<div className="notice notice--error form-grid__wide">{error}</div>}<Actions saving={saving} onClose={onClose}/></form></Drawer>}
function ReceiptDrawer({businessId,userId,purchaseId,item,locations,onClose,onSaved}:{businessId:string;userId:string;purchaseId:string;item:Item;locations:Location[];onClose:()=>void;onSaved:()=>Promise<void>}){const pending=Math.max(n(item.quantity_ordered)-n(item.quantity_received),0);const [location,setLocation]=useState('');const [quantity,setQuantity]=useState(String(pending));const [cost,setCost]=useState(String(item.unit_cost));const [lot,setLot]=useState('');const [notes,setNotes]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);setError(null);const q=Number(quantity);if(q<=0||q>pending){setError(`La recepción debe ser mayor a 0 y no exceder ${pending}.`);setSaving(false);return}const {data:receipt,error:rError}=await supabase.from('purchase_receipts').insert({business_id:businessId,purchase_id:purchaseId,location_id:location,received_by:userId,notes:notes||null}).select('id').single();if(rError||!receipt){setError(rError?.message??'No se pudo crear la recepción.');setSaving(false);return}const {error:iError}=await supabase.from('purchase_receipt_items').insert({business_id:businessId,receipt_id:receipt.id,purchase_item_id:item.id,material_variant_id:item.material_variant_id,quantity_received:q,unit_cost:Number(cost),lot_number:lot||null});if(iError){await supabase.from('purchase_receipts').delete().eq('id',receipt.id);setError(iError.message);setSaving(false);return}await onSaved()}return <Drawer title="Registrar recepción" onClose={onClose}><div className="notice"><PackagePlus size={18}/> Al guardar, Supabase crea el lote y movimiento de entrada automáticamente.</div><form className="form-grid" onSubmit={submit}><label className="form-grid__wide">Ubicación<select required value={location} onChange={e=>setLocation(e.target.value)}><option value="">Selecciona…</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Cantidad (pendiente {pending})<input required type="number" min="0.0001" max={pending} step="0.0001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Costo unitario<input required type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label className="form-grid__wide">Número de lote<input value={lot} onChange={e=>setLot(e.target.value)}/></label><label className="form-grid__wide">Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<div className="notice notice--error form-grid__wide">{error}</div>}<Actions saving={saving} onClose={onClose}/></form></Drawer>}
function Drawer({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="drawer-backdrop drawer-backdrop--top"><aside className="drawer"><div className="drawer__header"><div><span className="eyebrow">Compras</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={20}/></button></div>{children}</aside></div>}
function Actions({saving,onClose}:{saving:boolean;onClose:()=>void}){return <div className="form-actions form-grid__wide"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button disabled={saving} className="primary-button primary-button--inline">{saving?'Guardando…':'Guardar'}</button></div>}
