import { useEffect,useMemo,useState } from 'react'
import { BarChart3 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Row=Record<string,any>
type Attr={id:string;name:string;code:string}
type AttrValue={id:string;attribute_id:string;value:string}
type VariantValue={product_variant_id:string;attribute_id:string;value_id:string}
type OrderItem={product_id:string;product_variant_id:string|null;quantity:number|string;line_total:number|string;order_id:string}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const n=(v:unknown)=>Number(v??0)||0

export function ReportsPage({businessId}:{businessId:string}){
 const[attrs,setAttrs]=useState<Attr[]>([]),[values,setValues]=useState<AttrValue[]>([]),[links,setLinks]=useState<VariantValue[]>([]),[items,setItems]=useState<OrderItem[]>([]),[products,setProducts]=useState<Record<string,string>>({}),[variants,setVariants]=useState<Record<string,Row>>({}),[error,setError]=useState<string|null>(null)
 async function load(){if(!supabase)return;setError(null);const[o,a,v,l,pv]=await Promise.all([
  supabase.from('orders').select('id').eq('business_id',businessId).is('deleted_at',null).neq('status','cancelled'),
  supabase.from('variant_attributes').select('id,name,code').eq('business_id',businessId).eq('active',true).in('code',['size','color','brand']),
  supabase.from('variant_attribute_values').select('id,attribute_id,value').eq('business_id',businessId).eq('active',true),
  supabase.from('product_variant_values').select('product_variant_id,attribute_id,value_id').eq('business_id',businessId),
  supabase.from('product_variants').select('id,product_id,sku,name').eq('business_id',businessId).eq('active',true)
 ]);const first=[o.error,a.error,v.error,l.error,pv.error].find(Boolean);if(first){setError(first?.message??'No se pudieron cargar los reportes');return}const orderIds=(o.data??[]).map(x=>x.id);let oi:OrderItem[]=[];if(orderIds.length){const q=await supabase.from('order_items').select('order_id,product_id,product_variant_id,quantity,line_total').eq('business_id',businessId).in('order_id',orderIds);if(q.error)setError(q.error.message);oi=(q.data??[]) as OrderItem[]}setItems(oi);setAttrs((a.data??[]) as Attr[]);setValues((v.data??[]) as AttrValue[]);setLinks((l.data??[]) as VariantValue[]);const variantRows=pv.data??[];setVariants(Object.fromEntries(variantRows.map(x=>[x.id,x])));const productIds=[...new Set([...variantRows.map(x=>x.product_id),...oi.map(x=>x.product_id)].filter(Boolean))];if(productIds.length){const pr=await supabase.from('products').select('id,name').in('id',productIds);setProducts(Object.fromEntries((pr.data??[]).map(x=>[x.id,x.name])))}else setProducts({})}
 useEffect(()=>{void load()},[businessId])
 const valueMap=useMemo(()=>Object.fromEntries(values.map(v=>[v.id,v])),[values]);const attrMap=useMemo(()=>Object.fromEntries(attrs.map(a=>[a.id,a])),[attrs]);const variantAttrs=useMemo(()=>{const m:Record<string,Record<string,string>>={};for(const link of links){const a=attrMap[link.attribute_id],v=valueMap[link.value_id];if(!a||!v)continue;(m[link.product_variant_id]??={})[a.code]=v.value}return m},[links,attrMap,valueMap]);
 const byProduct=useMemo(()=>{const out:Record<string,{name:string;qty:number;revenue:number;orders:Set<string>}>= {};for(const item of items){const key=item.product_id||'unknown';const row=(out[key]??={name:products[key]??'Producto',qty:0,revenue:0,orders:new Set<string>()});row.qty+=n(item.quantity);row.revenue+=n(item.line_total);row.orders.add(item.order_id)}return Object.entries(out).map(([id,row])=>({id,name:row.name,qty:row.qty,revenue:row.revenue,orders:row.orders.size})).sort((a,b)=>b.qty-a.qty||b.revenue-a.revenue)},[items,products]);
 const byAttribute=useMemo(()=>{const out:Record<string,Record<string,{qty:number;revenue:number}>>={};for(const item of items){if(!item.product_variant_id)continue;const va=variantAttrs[item.product_variant_id]??{};for(const code of ['size','color','brand']){const val=va[code];if(!val)continue;const target=(out[code]??={});const row=(target[val]??={qty:0,revenue:0});row.qty+=n(item.quantity);row.revenue+=n(item.line_total)}}return out},[items,variantAttrs]);
 const combos=useMemo(()=>{const out:Record<string,{label:string;qty:number;revenue:number}>={};for(const item of items){if(!item.product_variant_id)continue;const va=variantAttrs[item.product_variant_id]??{};const vr=variants[item.product_variant_id];const product=products[vr?.product_id]??products[item.product_id]??'Producto';const bits=[va.size,va.color,va.brand].filter(Boolean);if(!bits.length)continue;const key=`${product}|${bits.join('|')}`;const row=(out[key]??={label:`${product} · ${bits.join(' · ')}`,qty:0,revenue:0});row.qty+=n(item.quantity);row.revenue+=n(item.line_total)}return Object.values(out).sort((a,b)=>b.qty-a.qty)},[items,variantAttrs,variants,products]);
 return <><div className="page-heading"><div><span className="eyebrow">Análisis comercial</span><h1>Reportes</h1><p>Ventas por producto, frecuencia, tallas, colores, marcas y combinaciones realmente vendidas en pedidos no cancelados.</p></div></div>{error&&<div className="notice notice--error">{error}</div>}
 <div className="section-heading"><div><span className="eyebrow">Productos</span><h2>Ventas y frecuencia</h2></div></div><div className="data-card"><div className="data-list">{byProduct.length===0?<div className="empty-state"><BarChart3 size={26}/><strong>Sin ventas por producto</strong></div>:byProduct.map(r=><div className="data-row" key={r.id}><div className="data-row__main"><strong>{r.name}</strong><span>{r.qty.toLocaleString('es-MX')} unidades · {r.orders} pedido{r.orders===1?'':'s'}</span></div><div className="data-row__meta"><strong>{money.format(r.revenue)}</strong></div></div>)}</div></div>
 <div className="report-grid">{(['size','color','brand'] as const).map(code=><section className="data-card" key={code}><div className="panel__heading"><div><span className="eyebrow">Atributo</span><h2>{code==='size'?'Tallas':code==='color'?'Colores':'Marcas'}</h2></div></div><div className="data-list">{Object.entries(byAttribute[code]??{}).sort((a,b)=>b[1].qty-a[1].qty).map(([label,row])=><div className="data-row" key={label}><div className="data-row__main"><strong>{label}</strong><span>{row.qty.toLocaleString('es-MX')} unidades</span></div><div className="data-row__meta"><strong>{money.format(row.revenue)}</strong></div></div>)}{Object.keys(byAttribute[code]??{}).length===0&&<div className="empty-state"><BarChart3 size={26}/><strong>Sin ventas con este atributo</strong></div>}</div></section>)}</div><div className="section-heading"><div><span className="eyebrow">Combinaciones</span><h2>Talla + color + marca</h2></div></div><div className="data-card"><div className="data-list">{combos.length===0?<div className="empty-state"><BarChart3 size={26}/><strong>Sin combinaciones vendidas</strong></div>:combos.map(c=><div className="data-row" key={c.label}><div className="data-row__main"><strong>{c.label}</strong><span>{c.qty.toLocaleString('es-MX')} unidades</span></div><div className="data-row__meta"><strong>{money.format(c.revenue)}</strong></div></div>)}</div></div></>}
