import { FormEvent,useEffect,useMemo,useState } from 'react'
import { AlertTriangle, BarChart3 } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './modules.css'

type Row=Record<string,any>
type Attr={id:string;name:string;code:string}
type AttrValue={id:string;attribute_id:string;value:string}
type VariantValue={product_variant_id:string;attribute_id:string;value_id:string}
type OrderItem={product_id:string;product_variant_id:string|null;quantity:number|string;line_total:number|string;order_id:string}
type PricingSignal={product_id:string;product_name:string;base_price:number|string|null;orders_30d:number;units_30d:number|string;revenue_30d:number|string;actual_margin_pct:number|string|null;target_margin_pct:number|string|null;max_input_increase_pct:number|string|null;recommendation:string}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const n=(v:unknown)=>Number(v??0)||0

export function ReportsPage({businessId}:{businessId:string}){
 const[attrs,setAttrs]=useState<Attr[]>([]),[values,setValues]=useState<AttrValue[]>([]),[links,setLinks]=useState<VariantValue[]>([]),[items,setItems]=useState<OrderItem[]>([]),[products,setProducts]=useState<Record<string,string>>({}),[variants,setVariants]=useState<Record<string,Row>>({}),[signals,setSignals]=useState<PricingSignal[]>([]),[targetMargin,setTargetMargin]=useState(''),[demandOrders,setDemandOrders]=useState(''),[demandUnits,setDemandUnits]=useState(''),[savingPolicy,setSavingPolicy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null)
 async function load(){if(!supabase)return;setError(null);const[o,a,v,l,pv,sg,b]=await Promise.all([
  supabase.from('orders').select('id').eq('business_id',businessId).is('deleted_at',null).neq('status','cancelled'),
  supabase.from('variant_attributes').select('id,name,code').eq('business_id',businessId).eq('active',true).in('code',['size','color','brand']),
  supabase.from('variant_attribute_values').select('id,attribute_id,value').eq('business_id',businessId).eq('active',true),
  supabase.from('product_variant_values').select('product_variant_id,attribute_id,value_id').eq('business_id',businessId),
  supabase.from('product_variants').select('id,product_id,sku,name').eq('business_id',businessId).eq('active',true),
  supabase.from('product_pricing_signals').select('product_id,product_name,base_price,orders_30d,units_30d,revenue_30d,actual_margin_pct,target_margin_pct,max_input_increase_pct,recommendation').eq('business_id',businessId).order('orders_30d',{ascending:false}),
  supabase.from('businesses').select('target_margin_pct,high_demand_orders_30d,high_demand_units_30d').eq('id',businessId).single()
 ]);const first=[o.error,a.error,v.error,l.error,pv.error,sg.error,b.error].find(Boolean);if(first){setError(first?.message??'No se pudieron cargar los reportes');return}const orderIds=(o.data??[]).map(x=>x.id);let oi:OrderItem[]=[];if(orderIds.length){const q=await supabase.from('order_items').select('order_id,product_id,product_variant_id,quantity,line_total').eq('business_id',businessId).in('order_id',orderIds);if(q.error)setError(q.error.message);oi=(q.data??[]) as OrderItem[]}setItems(oi);setAttrs((a.data??[]) as Attr[]);setValues((v.data??[]) as AttrValue[]);setLinks((l.data??[]) as VariantValue[]);setSignals((sg.data??[]) as PricingSignal[]);setTargetMargin(b.data?.target_margin_pct==null?'':String(b.data.target_margin_pct));setDemandOrders(b.data?.high_demand_orders_30d==null?'':String(b.data.high_demand_orders_30d));setDemandUnits(b.data?.high_demand_units_30d==null?'':String(b.data.high_demand_units_30d));const variantRows=pv.data??[];setVariants(Object.fromEntries(variantRows.map(x=>[x.id,x])));const productIds=[...new Set([...variantRows.map(x=>x.product_id),...oi.map(x=>x.product_id)].filter(Boolean))];if(productIds.length){const pr=await supabase.from('products').select('id,name').in('id',productIds);setProducts(Object.fromEntries((pr.data??[]).map(x=>[x.id,x.name])))}else setProducts({})}
 useEffect(()=>{void load()},[businessId])
 async function savePolicy(e:FormEvent){e.preventDefault();if(!supabase)return;setSavingPolicy(true);setError(null);setMessage(null);const payload={target_margin_pct:targetMargin===''?null:Number(targetMargin),high_demand_orders_30d:demandOrders===''?null:Number(demandOrders),high_demand_units_30d:demandUnits===''?null:Number(demandUnits)};const{error}=await supabase.from('businesses').update(payload).eq('id',businessId);setSavingPolicy(false);if(error){setError(error.message);return}setMessage('Reglas de recomendación actualizadas.');await load()}
 const valueMap=useMemo(()=>Object.fromEntries(values.map(v=>[v.id,v])),[values]);const attrMap=useMemo(()=>Object.fromEntries(attrs.map(a=>[a.id,a])),[attrs]);const variantAttrs=useMemo(()=>{const m:Record<string,Record<string,string>>={};for(const link of links){const a=attrMap[link.attribute_id],v=valueMap[link.value_id];if(!a||!v)continue;(m[link.product_variant_id]??={})[a.code]=v.value}return m},[links,attrMap,valueMap]);
 const byProduct=useMemo(()=>{const out:Record<string,{name:string;qty:number;revenue:number;orders:Set<string>}>= {};for(const item of items){const key=item.product_id||'unknown';const row=(out[key]??={name:products[key]??'Producto',qty:0,revenue:0,orders:new Set<string>()});row.qty+=n(item.quantity);row.revenue+=n(item.line_total);row.orders.add(item.order_id)}return Object.entries(out).map(([id,row])=>({id,name:row.name,qty:row.qty,revenue:row.revenue,orders:row.orders.size})).sort((a,b)=>b.qty-a.qty||b.revenue-a.revenue)},[items,products]);
 const byAttribute=useMemo(()=>{const out:Record<string,Record<string,{qty:number;revenue:number}>>={};for(const item of items){if(!item.product_variant_id)continue;const va=variantAttrs[item.product_variant_id]??{};for(const code of ['size','color','brand']){const val=va[code];if(!val)continue;const target=(out[code]??={});const row=(target[val]??={qty:0,revenue:0});row.qty+=n(item.quantity);row.revenue+=n(item.line_total)}}return out},[items,variantAttrs]);
 const combos=useMemo(()=>{const out:Record<string,{label:string;qty:number;revenue:number}>={};for(const item of items){if(!item.product_variant_id)continue;const va=variantAttrs[item.product_variant_id]??{};const vr=variants[item.product_variant_id];const product=products[vr?.product_id]??products[item.product_id]??'Producto';const bits=[va.size,va.color,va.brand].filter(Boolean);if(!bits.length)continue;const key=`${product}|${bits.join('|')}`;const row=(out[key]??={label:`${product} · ${bits.join(' · ')}`,qty:0,revenue:0});row.qty+=n(item.quantity);row.revenue+=n(item.line_total)}return Object.values(out).sort((a,b)=>b.qty-a.qty)},[items,variantAttrs,variants,products]);
 return <><div className="page-heading"><div><span className="eyebrow">Análisis comercial</span><h1>Reportes</h1><p>Ventas, frecuencia, atributos y señales de revisión de precio basadas en datos reales.</p></div></div>{error&&<div className="notice notice--error">{error}</div>}{message&&<div className="notice">{message}</div>}
 <form className="panel entity-form" onSubmit={savePolicy}><div><span className="eyebrow">Reglas configurables</span><h2>Cómo evaluar precio y demanda</h2><p>Déjalas vacías si todavía no quieres usar ese criterio.</p></div><div className="form-grid"><label>Margen objetivo %<input type="number" min="0" max="100" step="0.1" value={targetMargin} onChange={e=>setTargetMargin(e.target.value)} placeholder="Ej. 35"/></label><label>Pedidos en 30 días = demanda alta<input type="number" min="1" step="1" value={demandOrders} onChange={e=>setDemandOrders(e.target.value)} placeholder="Opcional"/></label><label>Unidades en 30 días = demanda alta<input type="number" min="0.01" step="0.01" value={demandUnits} onChange={e=>setDemandUnits(e.target.value)} placeholder="Opcional"/></label></div><button className="primary-button primary-button--auto" disabled={savingPolicy}>{savingPolicy?'Guardando…':'Guardar reglas'}</button></form>
 <div className="section-heading"><div><span className="eyebrow">Precios y margen</span><h2>Recomendaciones</h2><p>No cambian precios automáticamente; señalan qué conviene revisar.</p></div></div><div className="data-card"><div className="data-list">{signals.length===0?<div className="empty-state"><BarChart3 size={26}/><strong>Sin señales de precio</strong></div>:signals.map(r=><div className="data-row" key={r.product_id}><div className="data-row__avatar"><AlertTriangle size={18}/></div><div className="data-row__main"><strong>{r.product_name}</strong><span>{r.recommendation}</span><small>30 días: {n(r.orders_30d)} pedidos · {n(r.units_30d).toLocaleString('es-MX')} unidades{r.actual_margin_pct==null?'':` · margen ${n(r.actual_margin_pct).toFixed(1)}%`}{r.max_input_increase_pct==null?'':` · insumo +${n(r.max_input_increase_pct).toFixed(1)}%`}</small></div><div className="data-row__meta"><strong>{r.base_price==null?'Sin precio base':money.format(n(r.base_price))}</strong></div></div>)}</div></div>
 <div className="section-heading"><div><span className="eyebrow">Productos</span><h2>Ventas y frecuencia</h2></div></div><div className="data-card"><div className="data-list">{byProduct.length===0?<div className="empty-state"><BarChart3 size={26}/><strong>Sin ventas por producto</strong></div>:byProduct.map(r=><div className="data-row" key={r.id}><div className="data-row__main"><strong>{r.name}</strong><span>{r.qty.toLocaleString('es-MX')} unidades · {r.orders} pedido{r.orders===1?'':'s'}</span></div><div className="data-row__meta"><strong>{money.format(r.revenue)}</strong></div></div>)}</div></div>
 <div className="report-grid">{(['size','color','brand'] as const).map(code=><section className="data-card" key={code}><div className="panel__heading"><div><span className="eyebrow">Atributo</span><h2>{code==='size'?'Tallas':code==='color'?'Colores':'Marcas'}</h2></div></div><div className="data-list">{Object.entries(byAttribute[code]??{}).sort((a,b)=>b[1].qty-a[1].qty).map(([label,row])=><div className="data-row" key={label}><div className="data-row__main"><strong>{label}</strong><span>{row.qty.toLocaleString('es-MX')} unidades</span></div><div className="data-row__meta"><strong>{money.format(row.revenue)}</strong></div></div>)}{Object.keys(byAttribute[code]??{}).length===0&&<div className="empty-state"><BarChart3 size={26}/><strong>Sin ventas con este atributo</strong></div>}</div></section>)}</div><div className="section-heading"><div><span className="eyebrow">Combinaciones</span><h2>Talla + color + marca</h2></div></div><div className="data-card"><div className="data-list">{combos.length===0?<div className="empty-state"><BarChart3 size={26}/><strong>Sin combinaciones vendidas</strong></div>:combos.map(c=><div className="data-row" key={c.label}><div className="data-row__main"><strong>{c.label}</strong><span>{c.qty.toLocaleString('es-MX')} unidades</span></div><div className="data-row__meta"><strong>{money.format(c.revenue)}</strong></div></div>)}</div></div></>}
