import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Building2, CheckCircle2, ChevronRight, CircleDollarSign, MapPin, PackagePlus, RefreshCw, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './setup.css'

type SetupStatus={branches:number;locations:number;accounts:number;materials:number;paymentMethods:number}
type Manager='branches'|'locations'|'paymentMethods'|null
type Branch={id:string;name:string;address:string|null;active:boolean}
type Location={id:string;branch_id:string;name:string;location_type:string|null;active:boolean}
type PaymentMethod={id:string;name:string;method_type:string;active:boolean}
const emptyStatus:SetupStatus={branches:0,locations:0,accounts:0,materials:0,paymentMethods:0}
const methodLabels:Record<string,string>={cash:'Efectivo',transfer:'Transferencia',mercado_pago:'Mercado Pago',card:'Tarjeta',deposit:'Depósito',other:'Otro'}

export function SetupPage({businessId}:{businessId:string}){
 const[status,setStatus]=useState<SetupStatus>(emptyStatus),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null)
 const[manager,setManager]=useState<Manager>(null),[branches,setBranches]=useState<Branch[]>([]),[locations,setLocations]=useState<Location[]>([]),[paymentMethods,setPaymentMethods]=useState<PaymentMethod[]>([]),[editingId,setEditingId]=useState<string|null>(null),[editName,setEditName]=useState(''),[editExtra,setEditExtra]=useState(''),[editType,setEditType]=useState('cash'),[editActive,setEditActive]=useState(true),[managerLoading,setManagerLoading]=useState(false)
 const[branchName,setBranchName]=useState(''),[branchAddress,setBranchAddress]=useState(''),[areaName,setAreaName]=useState(''),[locationName,setLocationName]=useState(''),[locationType,setLocationType]=useState('storage'),[accountName,setAccountName]=useState(''),[accountType,setAccountType]=useState('cash'),[openingBalance,setOpeningBalance]=useState('0'),[materialName,setMaterialName]=useState(''),[variantName,setVariantName]=useState('Estándar'),[unit,setUnit]=useState('pieza'),[category,setCategory]=useState(''),[minimumStock,setMinimumStock]=useState('0')
 const loadStatus=useCallback(async()=>{if(!supabase)return;setLoading(true);setError(null);const[b,l,a,m,p]=await Promise.all([supabase.from('branches').select('id',{count:'exact',head:true}).eq('business_id',businessId).eq('active',true),supabase.from('locations').select('id',{count:'exact',head:true}).eq('business_id',businessId).eq('active',true),supabase.from('financial_accounts').select('id',{count:'exact',head:true}).eq('business_id',businessId).eq('active',true),supabase.from('materials').select('id',{count:'exact',head:true}).eq('business_id',businessId).is('deleted_at',null).eq('active',true),supabase.from('payment_methods').select('id',{count:'exact',head:true}).eq('business_id',businessId).eq('active',true)]);const e=b.error??l.error??a.error??m.error??p.error;if(e)setError(e.message);setStatus({branches:b.count??0,locations:l.count??0,accounts:a.count??0,materials:m.count??0,paymentMethods:p.count??0});setLoading(false)},[businessId])
 const loadManager=useCallback(async(kind:Exclude<Manager,null>)=>{if(!supabase)return;setManagerLoading(true);setError(null);if(kind==='branches'){const{data,error}=await supabase.from('branches').select('id,name,address,active').eq('business_id',businessId).order('name');if(error)setError(error.message);setBranches((data??[]) as Branch[])}if(kind==='locations'){const{data,error}=await supabase.from('locations').select('id,branch_id,name,location_type,active').eq('business_id',businessId).order('name');if(error)setError(error.message);setLocations((data??[]) as Location[])}if(kind==='paymentMethods'){const{data,error}=await supabase.from('payment_methods').select('id,name,method_type,active').eq('business_id',businessId).order('created_at');if(error)setError(error.message);setPaymentMethods((data??[]) as PaymentMethod[])}setManagerLoading(false)},[businessId])
 useEffect(()=>{void loadStatus()},[loadStatus])
 async function openManager(kind:Exclude<Manager,null>){setManager(kind);setEditingId(null);await loadManager(kind)}
 function startEdit(kind:Exclude<Manager,null>,row:Branch|Location|PaymentMethod){setEditingId(row.id);setEditName(row.name);setEditActive(row.active);if(kind==='branches')setEditExtra((row as Branch).address??'');if(kind==='locations')setEditType((row as Location).location_type??'other');if(kind==='paymentMethods')setEditType((row as PaymentMethod).method_type)}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!supabase||!manager||!editingId)return;setError(null);let q;if(manager==='branches')q=supabase.from('branches').update({name:editName.trim(),address:editExtra.trim()||null,active:editActive}).eq('id',editingId).eq('business_id',businessId);else if(manager==='locations')q=supabase.from('locations').update({name:editName.trim(),location_type:editType,active:editActive}).eq('id',editingId).eq('business_id',businessId);else q=supabase.from('payment_methods').update({name:editName.trim(),method_type:editType,active:editActive}).eq('id',editingId).eq('business_id',businessId);const{error}=await q;if(error){setError(error.message);return}setEditingId(null);setMessage('Cambios guardados.');await Promise.all([loadManager(manager),loadStatus()])}
 async function createBranch(e:FormEvent){e.preventDefault();if(!supabase)return;setError(null);setMessage(null);const{data:branch,error:be}=await supabase.from('branches').insert({business_id:businessId,name:branchName.trim(),address:branchAddress.trim()||null}).select('id').single();if(be||!branch){setError(be?.message??'No se pudo crear la sucursal.');return}let areaId:string|null=null;if(areaName.trim()){const{data:area,error:ae}=await supabase.from('areas').insert({business_id:businessId,branch_id:branch.id,name:areaName.trim()}).select('id').single();if(ae){setError(`Sucursal creada, pero el área falló: ${ae.message}`);await loadStatus();return}areaId=area?.id??null}if(locationName.trim()){const{error:le}=await supabase.from('locations').insert({business_id:businessId,branch_id:branch.id,area_id:areaId,name:locationName.trim(),location_type:locationType||null});if(le){setError(`Sucursal creada, pero la ubicación falló: ${le.message}`);await loadStatus();return}}setBranchName('');setBranchAddress('');setAreaName('');setLocationName('');setMessage('Sucursal y ubicación guardadas.');await loadStatus()}
 async function createAccount(e:FormEvent){e.preventDefault();if(!supabase)return;const balance=Number(openingBalance);if(!Number.isFinite(balance)){setError('El saldo inicial no es válido.');return}const{error}=await supabase.from('financial_accounts').insert({business_id:businessId,name:accountName.trim(),account_type:accountType,opening_balance:balance,currency:'MXN'});if(error){setError(error.message);return}setAccountName('');setOpeningBalance('0');setMessage('Cuenta financiera guardada.');await loadStatus()}
 async function createMaterial(e:FormEvent){e.preventDefault();if(!supabase)return;const min=Number(minimumStock);if(!Number.isFinite(min)||min<0){setError('El stock mínimo debe ser 0 o mayor.');return}const{data:material,error:me}=await supabase.from('materials').insert({business_id:businessId,name:materialName.trim(),unit,base_unit:unit,category:category.trim()||null,minimum_stock:min,track_inventory:true}).select('id').single();if(me||!material){setError(me?.message??'No se pudo crear el material.');return}const{error:ve}=await supabase.from('material_variants').insert({business_id:businessId,material_id:material.id,name:variantName.trim()||'Estándar'});if(ve){setError(`Material creado, pero la variante falló: ${ve.message}`);await loadStatus();return}setMaterialName('');setVariantName('Estándar');setCategory('');setMinimumStock('0');setMessage('Material y variante inicial guardados.');await loadStatus()}
 const completed=status.branches>0&&status.locations>0&&status.accounts>0&&status.materials>0&&status.paymentMethods>0
 return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Primera configuración</span><h1>Preparar Moore Print</h1><p>Completa sólo los datos reales del negocio. Nada se inventa ni se sobrescribe.</p></div><button className="secondary-button primary-button--auto" onClick={()=>void loadStatus()} disabled={loading}><RefreshCw size={16}/> Actualizar</button></div>{error&&<div className="notice notice--error">{error}</div>}{message&&<div className="notice">{message}</div>}{completed&&<div className="notice setup-complete"><CheckCircle2 size={18}/> La configuración mínima para probar operaciones ya está completa.</div>}<div className="setup-status-grid"><StatusCard icon={Building2} label="Sucursales" value={status.branches} ready={status.branches>0} onClick={()=>void openManager('branches')}/><StatusCard icon={MapPin} label="Ubicaciones" value={status.locations} ready={status.locations>0} onClick={()=>void openManager('locations')}/><StatusCard icon={CircleDollarSign} label="Cuentas" value={status.accounts} ready={status.accounts>0}/><StatusCard icon={PackagePlus} label="Materiales" value={status.materials} ready={status.materials>0}/><StatusCard icon={CheckCircle2} label="Métodos de pago" value={status.paymentMethods} ready={status.paymentMethods>0} onClick={()=>void openManager('paymentMethods')}/></div>
 <div className="setup-grid"><form className="panel entity-form" onSubmit={createBranch}><div><span className="eyebrow">Paso 1</span><h2>Sucursal y ubicación</h2></div><label>Nombre de sucursal<input value={branchName} onChange={e=>setBranchName(e.target.value)} required/></label><label>Dirección<input value={branchAddress} onChange={e=>setBranchAddress(e.target.value)}/></label><div className="form-grid"><label>Área<input value={areaName} onChange={e=>setAreaName(e.target.value)}/></label><label>Ubicación<input value={locationName} onChange={e=>setLocationName(e.target.value)} required/></label></div><label>Tipo<select value={locationType} onChange={e=>setLocationType(e.target.value)}><option value="storage">Almacén</option><option value="counter">Mostrador</option><option value="production">Producción</option><option value="office">Administración</option><option value="other">Otro</option></select></label><button className="primary-button">Guardar sucursal</button></form><form className="panel entity-form" onSubmit={createAccount}><div><span className="eyebrow">Paso 2</span><h2>Primera cuenta financiera</h2></div><label>Nombre<input value={accountName} onChange={e=>setAccountName(e.target.value)} required/></label><label>Tipo<select value={accountType} onChange={e=>setAccountType(e.target.value)}><option value="cash">Efectivo</option><option value="bank">Banco</option><option value="mercado_pago">Mercado Pago</option><option value="personal_business_use">Personal usada para negocio</option><option value="other">Otra</option></select></label><label>Saldo inicial MXN<input type="number" step="0.01" value={openingBalance} onChange={e=>setOpeningBalance(e.target.value)} required/></label><button className="primary-button">Guardar cuenta</button></form><form className="panel entity-form" onSubmit={createMaterial}><div><span className="eyebrow">Paso 3</span><h2>Primer material</h2></div><label>Material<input value={materialName} onChange={e=>setMaterialName(e.target.value)} required/></label><div className="form-grid"><label>Variante<input value={variantName} onChange={e=>setVariantName(e.target.value)} required/></label><label>Unidad<input value={unit} onChange={e=>setUnit(e.target.value)} required/></label></div><div className="form-grid"><label>Categoría<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Stock mínimo<input type="number" min="0" step="0.01" value={minimumStock} onChange={e=>setMinimumStock(e.target.value)} required/></label></div><button className="primary-button">Guardar material</button></form></div>
 {manager&&<div className="modal-backdrop" onClick={()=>setManager(null)}><section className="modal-card setup-manager" onClick={e=>e.stopPropagation()}><div className="modal-card__header"><div><span className="eyebrow">Configuración</span><h2>{manager==='branches'?'Sucursales':manager==='locations'?'Ubicaciones':'Métodos de pago'}</h2></div><button className="icon-button" onClick={()=>setManager(null)}><X size={20}/></button></div>{managerLoading?<div className="empty-state">Cargando…</div>:<div className="setup-manager-list">{(manager==='branches'?branches:manager==='locations'?locations:paymentMethods).map((row:any)=><button type="button" className="setup-manager-row" key={row.id} onClick={()=>startEdit(manager,row)}><div><strong>{row.name}</strong><span>{manager==='branches'?(row.address||'Sin dirección'):manager==='locations'?(row.location_type||'Sin tipo'):methodLabels[row.method_type]??row.method_type}</span></div><span className={`badge ${row.active?'badge--success':''}`}>{row.active?'Activo':'Inactivo'}</span><ChevronRight size={17}/></button>)}</div>}{editingId&&<form className="entity-form setup-edit-form" onSubmit={saveEdit}><h3>Editar</h3><label>Nombre<input required value={editName} onChange={e=>setEditName(e.target.value)}/></label>{manager==='branches'&&<label>Dirección<input value={editExtra} onChange={e=>setEditExtra(e.target.value)}/></label>}{manager==='locations'&&<label>Tipo<select value={editType} onChange={e=>setEditType(e.target.value)}><option value="storage">Almacén</option><option value="counter">Mostrador</option><option value="production">Producción</option><option value="office">Administración</option><option value="other">Otro</option></select></label>}{manager==='paymentMethods'&&<label>Tipo<select value={editType} onChange={e=>setEditType(e.target.value)}><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="mercado_pago">Mercado Pago</option><option value="card">Tarjeta</option><option value="deposit">Depósito</option><option value="other">Otro</option></select></label>}<label className="checkbox-field"><input type="checkbox" checked={editActive} onChange={e=>setEditActive(e.target.checked)}/> Activo</label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditingId(null)}>Cancelar</button><button className="primary-button">Guardar cambios</button></div></form>}</section></div>}</>
}
function StatusCard({icon:Icon,label,value,ready,onClick}:{icon:typeof Building2;label:string;value:number;ready:boolean;onClick?:()=>void}){const content=<><Icon size={19}/><div><span>{label}</span><strong>{value}</strong></div>{onClick?<ChevronRight size={18}/>:ready?<CheckCircle2 size={17}/>:null}</>;return onClick?<button type="button" className={`setup-status setup-status--button ${ready?'setup-status--ready':''}`} onClick={onClick}>{content}</button>:<article className={`setup-status ${ready?'setup-status--ready':''}`}>{content}</article>}
