import { FormEvent, useEffect, useMemo, useState } from 'react'
import { PackageCheck, Plus, Search, Star, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import './finance-suppliers.css'

type Supplier={id:string;name:string;contact_name:string|null;phone:string|null;email:string|null;tax_id:string|null;address:string|null;notes:string|null;active:boolean}
type Performance={supplier_id:string;name:string;delivery_rating:number|string|null;accuracy_rating:number|string|null;quality_rating:number|string|null;incident_count:number|string|null;purchase_count:number|string|null;purchase_value:number|string|null}
type MaterialLink={id:string;supplier_id:string;material_id:string;preferred:boolean;brand:string|null;estimated_lead_days:number|null;current_price:number|string|null;currency:string;materials:{name:string}|null}
type Incident={id:string;supplier_id:string;incident_type:string;resolution:string|null;description:string|null;resolved_at:string|null;created_at:string}
type Material={id:string;name:string}
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'})
const num=(v:unknown)=>Number.isFinite(Number(v??0))?Number(v??0):0

export function SuppliersPage({businessId,userId}:{businessId:string;userId:string}){
 const [suppliers,setSuppliers]=useState<Supplier[]>([]),[performance,setPerformance]=useState<Performance[]>([]),[links,setLinks]=useState<MaterialLink[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[materials,setMaterials]=useState<Material[]>([])
 const [query,setQuery]=useState(''),[selected,setSelected]=useState<Supplier|null>(null),[modal,setModal]=useState<'supplier'|'material'|'incident'|null>(null),[editing,setEditing]=useState<Supplier|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null)
 async function load(){if(!supabase)return;setLoading(true);setError(null);const [s,p,l,i,m]=await Promise.all([
  supabase.from('suppliers').select('id,name,contact_name,phone,email,tax_id,address,notes,active').eq('business_id',businessId).is('deleted_at',null).order('name'),
  supabase.from('supplier_performance').select('*').eq('business_id',businessId),
  supabase.from('supplier_materials').select('id,supplier_id,material_id,preferred,brand,estimated_lead_days,current_price,currency,materials(name)').eq('business_id',businessId).eq('active',true),
  supabase.from('supplier_incidents').select('id,supplier_id,incident_type,resolution,description,resolved_at,created_at').eq('business_id',businessId).order('created_at',{ascending:false}).limit(100),
  supabase.from('materials').select('id,name').eq('business_id',businessId).is('deleted_at',null).eq('active',true).order('name')]);const first=[s,p,l,i,m].find(r=>r.error);if(first?.error)setError(first.error.message);setSuppliers((s.data??[]) as Supplier[]);setPerformance((p.data??[]) as Performance[]);setLinks((l.data??[]) as unknown as MaterialLink[]);setIncidents((i.data??[]) as Incident[]);setMaterials((m.data??[]) as Material[]);setLoading(false)}
 useEffect(()=>{void load()},[businessId])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return suppliers.filter(s=>!q||[s.name,s.contact_name,s.phone,s.email].some(v=>v?.toLowerCase().includes(q)))},[suppliers,query])
 const perf=(id:string)=>performance.find(p=>p.supplier_id===id)
 const selectedLinks=selected?links.filter(x=>x.supplier_id===selected.id):[],selectedIncidents=selected?incidents.filter(x=>x.supplier_id===selected.id):[]
 return <><div className="page-heading page-heading--actions"><div><span className="eyebrow">Abastecimiento</span><h1>Proveedores</h1><p>Contactos, materiales, precios y desempeño.</p></div><button className="primary-button primary-button--auto" onClick={()=>{setEditing(null);setModal('supplier')}}><Plus size={17}/>Nuevo proveedor</button></div>
 <div className="toolbar"><div className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar proveedor…"/></div><span className="toolbar__count">{visible.length} proveedores</span></div>{error&&<div className="notice notice--error">{error}</div>}
 <div className="data-card"><div className="data-list">{loading?<div className="empty-state">Cargando…</div>:visible.length===0?<div className="empty-state"><PackageCheck size={28}/><strong>Sin proveedores</strong></div>:visible.map(s=>{const p=perf(s.id);const rating=[num(p?.delivery_rating),num(p?.accuracy_rating),num(p?.quality_rating)].filter(v=>v>0);const avg=rating.length?rating.reduce((a,b)=>a+b,0)/rating.length:0;return <button className="data-row" key={s.id} onClick={()=>setSelected(s)}><div className="data-row__avatar"><PackageCheck size={18}/></div><div className="data-row__main"><strong>{s.name}</strong><span>{s.contact_name||'Sin contacto'} · {s.phone||'Sin teléfono'}</span></div><div className="data-row__meta"><strong>{p?money.format(num(p.purchase_value)):'$0.00'}</strong><span>{p?.purchase_count??0} compras · {avg?`${avg.toFixed(1)}★`:'Sin evaluación'}</span></div></button>})}</div></div>
 {selected&&<div className="drawer-backdrop"><aside className="detail-drawer detail-drawer--wide"><div className="drawer-header"><div><span className="eyebrow">Proveedor</span><h2>{selected.name}</h2><p>{selected.contact_name||'Sin contacto'}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="supplier-actions"><button className="secondary-button" onClick={()=>{setEditing(selected);setModal('supplier')}}>Editar</button><button className="secondary-button" onClick={()=>setModal('material')}>Agregar material</button><button className="secondary-button" onClick={()=>setModal('incident')}>Registrar incidencia</button></div><div className="detail-stack"><div className="detail-item"><div><span>Teléfono</span><strong>{selected.phone||'—'}</strong></div></div><div className="detail-item"><div><span>Correo</span><strong>{selected.email||'—'}</strong></div></div><div className="detail-item"><div><span>RFC</span><strong>{selected.tax_id||'—'}</strong></div></div><div className="detail-item"><div><span>Dirección</span><strong>{selected.address||'—'}</strong></div></div></div><section className="drawer-section"><h3>Desempeño</h3>{(()=>{const p=perf(selected.id);return p?<div className="supplier-metrics"><div><Star size={16}/><span>Entrega</span><strong>{num(p.delivery_rating).toFixed(1)}</strong></div><div><Star size={16}/><span>Exactitud</span><strong>{num(p.accuracy_rating).toFixed(1)}</strong></div><div><Star size={16}/><span>Calidad</span><strong>{num(p.quality_rating).toFixed(1)}</strong></div><div><span>Incidencias</span><strong>{p.incident_count??0}</strong></div></div>:<div className="empty-state empty-state--compact">Sin evaluaciones todavía.</div>})()}</section><section className="drawer-section"><h3>Materiales y precios</h3>{selectedLinks.length===0?<div className="empty-state empty-state--compact">Sin materiales asociados.</div>:<div className="line-items">{selectedLinks.map(x=><div className="line-item" key={x.id}><div><strong>{x.materials?.name??'Material'}</strong><span>{x.brand||'Sin marca'} · {x.estimated_lead_days??'—'} días</span></div><div><strong>{x.current_price==null?'Sin precio':money.format(num(x.current_price))}</strong><span>{x.preferred?'Preferido':'Alternativo'}</span></div></div>)}</div>}</section><section className="drawer-section"><h3>Incidencias recientes</h3>{selectedIncidents.length===0?<div className="empty-state empty-state--compact">Sin incidencias.</div>:<div className="line-items">{selectedIncidents.slice(0,8).map(x=><div className="line-item" key={x.id}><div><strong>{x.incident_type}</strong><span>{x.description||'Sin descripción'}</span></div><div><span>{x.resolution||'Pendiente'}</span></div></div>)}</div>}</section></aside></div>}
 {modal==='supplier'&&<SupplierModal businessId={businessId} editing={editing} close={()=>setModal(null)} done={async()=>{setModal(null);await load();if(editing)setSelected(null)}}/>}
 {modal==='material'&&selected&&<MaterialModal businessId={businessId} supplierId={selected.id} materials={materials} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}
 {modal==='incident'&&selected&&<IncidentModal businessId={businessId} supplierId={selected.id} userId={userId} close={()=>setModal(null)} done={async()=>{setModal(null);await load()}}/>}</>}

function SupplierModal({businessId,editing,close,done}:{businessId:string;editing:Supplier|null;close:()=>void;done:()=>void}){const [name,setName]=useState(editing?.name??''),[contact,setContact]=useState(editing?.contact_name??''),[phone,setPhone]=useState(editing?.phone??''),[email,setEmail]=useState(editing?.email??''),[tax,setTax]=useState(editing?.tax_id??''),[address,setAddress]=useState(editing?.address??''),[notes,setNotes]=useState(editing?.notes??''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const payload={business_id:businessId,name,contact_name:contact||null,phone:phone||null,email:email||null,tax_id:tax||null,address:address||null,notes:notes||null};const result=editing?await supabase.from('suppliers').update(payload).eq('id',editing.id).eq('business_id',businessId):await supabase.from('suppliers').insert(payload);if(result.error)setError(result.error.message);else done()}return <Modal title={editing?'Editar proveedor':'Nuevo proveedor'} close={close}><form className="entity-form" onSubmit={submit}><div className="form-grid"><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Contacto<input value={contact} onChange={e=>setContact(e.target.value)}/></label><label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>RFC<input value={tax} onChange={e=>setTax(e.target.value)}/></label><label>Dirección<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="form-span-2">Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Modal>}
function MaterialModal({businessId,supplierId,materials,close,done}:{businessId:string;supplierId:string;materials:Material[];close:()=>void;done:()=>void}){const [material,setMaterial]=useState(''),[brand,setBrand]=useState(''),[price,setPrice]=useState(''),[days,setDays]=useState(''),[preferred,setPreferred]=useState(false),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('supplier_materials').insert({business_id:businessId,supplier_id:supplierId,material_id:material,brand:brand||null,current_price:price?num(price):null,estimated_lead_days:days?Number(days):null,preferred});if(error)setError(error.message);else done()}return <Modal title="Asociar material" close={close}><form className="entity-form" onSubmit={submit}><label>Material<select required value={material} onChange={e=>setMaterial(e.target.value)}><option value="">Selecciona</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="form-grid"><label>Marca<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Precio actual<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Días estimados<input type="number" min="0" value={days} onChange={e=>setDays(e.target.value)}/></label><label className="checkbox-field"><input type="checkbox" checked={preferred} onChange={e=>setPreferred(e.target.checked)}/> Proveedor preferido</label></div>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Modal>}
function IncidentModal({businessId,supplierId,userId,close,done}:{businessId:string;supplierId:string;userId:string;close:()=>void;done:()=>void}){const [type,setType]=useState('missing'),[description,setDescription]=useState(''),[error,setError]=useState<string|null>(null);async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from('supplier_incidents').insert({business_id:businessId,supplier_id:supplierId,incident_type:type,description:description||null,created_by:userId});if(error)setError(error.message);else done()}return <Modal title="Registrar incidencia" close={close}><form className="entity-form" onSubmit={submit}><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="missing">Faltante</option><option value="incorrect_product">Producto incorrecto</option><option value="damaged">Dañado</option><option value="extra">Extra</option><option value="other">Otro</option></select></label><label>Descripción<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label>{error&&<div className="notice notice--error">{error}</div>}<Actions close={close}/></form></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="form-modal form-modal--small"><div className="drawer-header"><h2>{title}</h2><button className="icon-button" onClick={close}><X size={19}/></button></div>{children}</div></div>}
function Actions({close}:{close:()=>void}){return <div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button primary-button--auto">Guardar</button></div>}
