import React,{useEffect,useState}from'react';
import{Plus,Eye,EyeOff,Save,X}from'lucide-react';
import{supabase}from'./lib/supabase';

const blank={label:'',field_key:'',field_type:'text',options:'',placeholder:'',unit:'',is_required:false,sort_order:10};
const keyify=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');

export default function ConfigurationEditor({product,onClose,onMessage}){
 const[fields,setFields]=useState([]),[form,setForm]=useState(blank),[busy,setBusy]=useState(false);
 const load=async()=>{const{data,error}=await supabase.from('product_configuration_fields').select('id,field_key,label,field_type,options,placeholder,unit,is_required,sort_order,is_active').eq('product_id',product.id).order('sort_order');if(error)onMessage(error.message);else setFields(data||[])};
 useEffect(()=>{load()},[product.id]);
 const create=async e=>{e.preventDefault();if(!form.label.trim()||busy)return;setBusy(true);const options=form.field_type==='select'?form.options.split(',').map(x=>x.trim()).filter(Boolean):[];if(form.field_type==='select'&&!options.length){onMessage('Agrega al menos una opción para el selector.');setBusy(false);return}const{error}=await supabase.from('product_configuration_fields').insert({product_id:product.id,label:form.label.trim(),field_key:keyify(form.field_key||form.label),field_type:form.field_type,options,placeholder:form.placeholder.trim()||null,unit:form.unit.trim()||null,is_required:form.is_required,sort_order:Number(form.sort_order)||10,is_active:true});onMessage(error?error.message:'Campo de configuración creado.');if(!error){setForm(blank);await load()}setBusy(false)};
 const toggle=async f=>{const{error}=await supabase.from('product_configuration_fields').update({is_active:!f.is_active}).eq('id',f.id);onMessage(error?error.message:(f.is_active?'Campo ocultado.':'Campo activado.'));if(!error)load()};
 const save=async f=>{const options=f.field_type==='select'?(Array.isArray(f.options)?f.options:[]):[];if(f.field_type==='select'&&!options.length){onMessage('El selector necesita al menos una opción.');return}const{error}=await supabase.from('product_configuration_fields').update({label:f.label,field_key:keyify(f.field_key||f.label),field_type:f.field_type,options,placeholder:f.placeholder||null,unit:f.unit||null,is_required:!!f.is_required,sort_order:Number(f.sort_order)||0}).eq('id',f.id);onMessage(error?error.message:'Configuración actualizada.');if(!error)load()};
 return <section className="configEditor"><div className="configHead"><div><small>CONFIGURACIÓN DEL COTIZADOR</small><h3>{product.name}</h3></div><button type="button" onClick={onClose}><X/></button></div><p>Define únicamente datos que el cliente debe proporcionar. Esto no asigna precios.</p><form onSubmit={create} className="configCreate"><input required placeholder="Nombre del campo, ej. Talla" value={form.label} onChange={e=>setForm({...form,label:e.target.value,field_key:keyify(e.target.value)})}/><select value={form.field_type} onChange={e=>setForm({...form,field_type:e.target.value})}><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista de opciones</option></select><input placeholder="Unidad opcional, ej. cm" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input placeholder="Texto de ayuda opcional" value={form.placeholder} onChange={e=>setForm({...form,placeholder:e.target.value})}/>{form.field_type==='select'&&<input className="wide" placeholder="Opciones separadas por coma" value={form.options} onChange={e=>setForm({...form,options:e.target.value})}/>}<label className="check"><input type="checkbox" checked={form.is_required} onChange={e=>setForm({...form,is_required:e.target.checked})}/> Obligatorio</label><button disabled={busy}><Plus size={17}/>Agregar campo</button></form><div className="configList">{fields.length===0?<p>Este producto todavía no solicita datos adicionales.</p>:fields.map((f,i)=><article key={f.id} className={!f.is_active?'inactive':''}><input value={f.label} onChange={e=>setFields(a=>a.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/><select value={f.field_type} onChange={e=>setFields(a=>a.map((x,j)=>j===i?{...x,field_type:e.target.value}:x))}><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista</option></select>{f.field_type==='select'&&<input value={(f.options||[]).join(', ')} onChange={e=>setFields(a=>a.map((x,j)=>j===i?{...x,options:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:x))} placeholder="Opciones separadas por coma"/>}<input value={f.unit||''} onChange={e=>setFields(a=>a.map((x,j)=>j===i?{...x,unit:e.target.value}:x))} placeholder="Unidad"/><label className="check"><input type="checkbox" checked={!!f.is_required} onChange={e=>setFields(a=>a.map((x,j)=>j===i?{...x,is_required:e.target.checked}:x))}/> Obligatorio</label><div className="configActions"><button type="button" onClick={()=>save(f)}><Save size={16}/>Guardar</button><button type="button" onClick={()=>toggle(f)}>{f.is_active?<><EyeOff size={16}/>Ocultar</>:<><Eye size={16}/>Activar</>}</button></div></article>)}</div></section>
}